"""MEDISCAN AI — Comprehensive Medicine Database (500+ entries)"""

def _m(cat, uses, dose, alt, warn, side_effects=[], safety_risk=3):
    return {"category": cat, "uses": uses, "dosage": dose, "alternatives": alt, "warnings": warn, "side_effects": side_effects, "safety_risk": safety_risk}

MEDICINE_DB = {

    # ═══════════════════════════════════════════════════════════
    # 1. ANALGESICS / ANTIPYRETICS / NSAIDs
    # ═══════════════════════════════════════════════════════════
    "paracetamol":       _m("Analgesic/Antipyretic",["Fever","Mild pain","Headache","Post-op pain"],"500–1000mg every 4–6h (max 4g/day)",["ibuprofen","aspirin"],["Avoid alcohol","Hepatotoxicity in overdose","Liver disease caution"], ['Nausea', 'Dizziness', 'Drowsiness'], 3),
    "ibuprofen":         _m("NSAID",["Pain","Inflammation","Fever","Arthritis","Dysmenorrhoea"],"200–400mg every 6–8h with food",["naproxen","diclofenac"],["Peptic ulcer risk","Renal failure caution","Cardiovascular risk","Avoid in pregnancy 3rd trimester"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "aspirin":           _m("NSAID/Antiplatelet",["Pain","Fever","Heart attack prevention","Stroke prevention"],"75–300mg daily",["clopidogrel","paracetamol"],["Reye syndrome in children","Bleeding risk","GI irritation","Avoid in dengue"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "diclofenac":        _m("NSAID",["Osteoarthritis","Rheumatoid arthritis","Acute pain","Renal colic"],"50mg TDS or 75mg BD",["ibuprofen","naproxen"],["GI bleeding","Hypertension","Renal impairment","Cardiovascular risk"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "naproxen":          _m("NSAID",["Arthritis","Muscle pain","Menstrual cramps","Gout"],"250–500mg BD",["ibuprofen","diclofenac"],["GI ulceration","Avoid in heart failure","Long half-life"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "nimesulide":        _m("NSAID (COX-2 selective)",["Fever","Acute pain","Dysmenorrhoea"],"100mg BD with food",["paracetamol","ibuprofen"],["Hepatotoxicity — avoid >15 days","Banned in children <12","GI upset"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "aceclofenac":       _m("NSAID",["Osteoarthritis","Rheumatoid arthritis","Musculoskeletal pain"],"100mg BD with food",["diclofenac","ibuprofen"],["GI upset","Cardiovascular risk","Renal impairment"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "mefenamic_acid":    _m("NSAID",["Dysmenorrhoea","Dental pain","Menorrhagia"],"500mg TDS with food (max 7 days)",["ibuprofen","naproxen"],["GI bleeding","Haemolytic anaemia","Max 7 days"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "piroxicam":         _m("NSAID",["Arthritis","Musculoskeletal pain","Gout"],"20mg OD",["meloxicam","diclofenac"],["GI ulceration","Long half-life — caution in elderly"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "meloxicam":         _m("NSAID (COX-2 preferential)",["Osteoarthritis","Rheumatoid arthritis"],"7.5–15mg OD with food",["piroxicam","celecoxib"],["Lower GI risk","Cardiovascular risk","Renal caution"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "etoricoxib":        _m("COX-2 Inhibitor",["Acute gout","Osteoarthritis","Dental pain"],"60–120mg OD",["celecoxib","diclofenac"],["Cardiovascular risk","Hypertension","Hepatotoxicity"], ['Common clinical side effects'], 3),
    "celecoxib":         _m("COX-2 Inhibitor",["Osteoarthritis","Rheumatoid arthritis","Familial adenomatous polyposis"],"100–200mg OD or BD",["etoricoxib","diclofenac"],["Cardiovascular risk","Sulfa allergy caution"], ['Common clinical side effects'], 3),
    "ketorolac":         _m("NSAID",["Post-operative pain","Moderate acute pain"],"10mg every 4–6h (max 5 days only)",["diclofenac","ibuprofen"],["Short-term use only","Renal risk","GI bleeding"], ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness'], 4),
    "tramadol":          _m("Opioid Analgesic",["Moderate-severe pain","Neuropathic pain"],"50–100mg every 4–6h",["morphine","codeine"],["Addiction risk","Seizures","Avoid with SSRIs (serotonin syndrome)"], ['Nausea', 'Dizziness', 'Drowsiness'], 5),
    "morphine":          _m("Opioid Analgesic",["Severe pain","Cancer pain","Post-op pain"],"2.5–10mg every 4h",["fentanyl","tramadol"],["Respiratory depression","Addiction","Constipation","Sedation"], ['Nausea', 'Dizziness', 'Drowsiness'], 5),
    "codeine":           _m("Opioid Analgesic",["Mild-moderate pain","Cough","Diarrhoea"],"15–60mg every 4–6h",["tramadol","paracetamol"],["Constipation","Drowsiness","Addiction risk","Avoid in children"], ['Nausea', 'Dizziness', 'Drowsiness'], 5),
    "fentanyl":          _m("Opioid Analgesic (Potent)",["Severe pain","Anaesthesia adjunct","Cancer pain (patch)"],"Patch: 25–100mcg/h; IV: as directed by anaesthetist",["morphine","oxycodone"],["Respiratory depression","Addiction","Serotonin syndrome","Chest wall rigidity (IV)"], ['Nausea', 'Dizziness', 'Drowsiness'], 5),
    "buprenorphine":     _m("Partial Opioid Agonist",["Moderate-severe pain","Opioid dependence (high dose SL)"],"Patch: 5–20mcg/h; SL 0.2–0.4mg TDS (pain)",["methadone","naloxone"],["Dependence (less than full agonists)","Respiratory depression","Ceiling effect"], ['Constipation', 'Sedation', 'Nausea', 'Dizziness'], 5),
    "tapentadol":        _m("Opioid + NRI Analgesic",["Moderate-severe pain","Diabetic neuropathic pain"],"50–100mg every 4–6h (max 600mg/day)",["tramadol","morphine"],["Seizures","Serotonin syndrome","Addiction risk","GI upset"], ['Nausea', 'Dizziness', 'Drowsiness'], 5),
    "drotaverine":       _m("Smooth Muscle Relaxant",["Biliary colic","Renal colic","IBS","Dysmenorrhoea"],"40–80mg TDS",["mebeverine","dicyclomine"],["Hypotension","Dizziness","Generally well tolerated"], ['Common clinical side effects'], 3),
    "dicyclomine":       _m("Anticholinergic Antispasmodic",["IBS","GI spasms","Infantile colic","Dysmenorrhoea"],"10–20mg TDS before meals",["drotaverine","hyoscine_butylbromide"],["Dry mouth","Blurred vision","Urinary retention","Avoid in elderly"], ['Common clinical side effects'], 3),
    "hyoscine_butylbromide": _m("Anticholinergic",["GI/biliary/renal colic","IBS"],"20mg IM/SC or 10mg TDS oral",["dicyclomine","drotaverine"],["Antimuscarinic effects","Tachycardia","Dry mouth"], ['Common clinical side effects'], 3),
    "serratiopeptidase": _m("Proteolytic Enzyme",["Post-op swelling","Sinusitis","Inflammation","Fibrocystic breast"],"10mg TDS on empty stomach",["trypsin_chymotrypsin"],["GI upset","Rare bleeding — avoid with anticoagulants"], ['Common clinical side effects'], 3),
    "trypsin_chymotrypsin": _m("Proteolytic Enzyme",["Post-op/traumatic oedema","Inflammatory swelling"],"1 tablet TDS on empty stomach",["serratiopeptidase"],["GI upset","Avoid with anticoagulants"], ['Common clinical side effects'], 3),
    "paracetamol_caffeine": _m("Analgesic + Stimulant (Combination)",["Tension headache","Migraine (mild)","Body aches with fatigue"],"2 tabs every 4–6h",["sumatriptan","ibuprofen"],["Caffeine dependence","Insomnia","GI upset"], ['Nausea', 'Dizziness', 'Drowsiness'], 3),
    "pregabalin":        _m("Anticonvulsant/Analgesic",["Neuropathic pain","Fibromyalgia","Epilepsy (adjunct)","GAD"],"75–300mg BD",["gabapentin","duloxetine"],["Dizziness","Sedation","Weight gain","Dependence potential","Oedema"], ['Nausea', 'Dizziness', 'Drowsiness'], 3),
    "gabapentin":        _m("Anticonvulsant/Analgesic",["Neuropathic pain","Postherpetic neuralgia","Epilepsy","Restless legs"],"300–1200mg TDS",["pregabalin","amitriptyline"],["Sedation","Dizziness","Peripheral oedema","Gradual dose titration"], ['Nausea', 'Dizziness', 'Drowsiness'], 3),
    "duloxetine":        _m("SNRI/Analgesic",["Diabetic neuropathy","Fibromyalgia","Depression","GAD","Stress incontinence"],"30–60mg OD",["pregabalin","amitriptyline"],["Nausea","Dry mouth","Hypertension","Hepatotoxicity","Serotonin syndrome"], ['Nausea', 'Dizziness', 'Drowsiness'], 3),
    "ziconotide":        _m("N-type Calcium Channel Blocker (Intrathecal)",["Severe chronic pain refractory to opioids"],"Intrathecal infusion — specialist only",["opioids","clonidine"],["Confusion","Dizziness","Hallucinations — specialist use only"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 2. ANTIBIOTICS — PENICILLINS
    # ═══════════════════════════════════════════════════════════
    "amoxicillin":       _m("Antibiotic (Penicillin)",["Bacterial infections","Pneumonia","Ear infection","UTI","H. pylori"],"500mg TDS for 5–7 days",["ampicillin","cefalexin"],["Penicillin allergy","Diarrhoea","Rash"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ampicillin":        _m("Antibiotic (Penicillin)",["Meningitis","Listeria","UTI","Endocarditis (with gentamicin)"],"250–500mg QID; IV 1–2g QID",["amoxicillin"],["Penicillin allergy","Ampicillin rash in EBV","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "amoxicillin_clavulanate": _m("Antibiotic (Penicillin + BLI)",["Sinusitis","Pneumonia","Skin infections","UTI","Animal bites"],"625mg TDS or 1g BD with food",["cefalexin","levofloxacin"],["GI upset","Cholestatic jaundice","Penicillin allergy"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "flucloxacillin":    _m("Antibiotic (Penicillinase Resistant)",["Staphylococcal infections","Cellulitis","Impetigo","Bone infections"],"500mg QID 30min before food",["cloxacillin","cefalexin"],["Penicillin allergy","Hepatotoxicity (prolonged)","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cloxacillin":       _m("Antibiotic (Penicillinase Resistant)",["Staphylococcal skin/bone infections"],"500mg QID",["flucloxacillin","cefalexin"],["Penicillin allergy","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "piperacillin_tazobactam": _m("Antibiotic (Penicillin + BLI)",["Severe hospital infections","Pseudomonas","Intra-abdominal sepsis","Febrile neutropenia"],"4.5g IV TDS–QID",["meropenem","ceftazidime"],["Penicillin allergy","Hypokalaemia","Seizures (high dose)"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "benzylpenicillin":  _m("Antibiotic (Penicillin G)",["Meningococcal meningitis","Streptococcal infections","Syphilis","Rheumatic fever prophylaxis"],"1.2–2.4g IV every 4h",["ampicillin","ceftriaxone"],["Penicillin allergy","Seizures (high dose)","Electrolyte load"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),

    # ═══════════════════════════════════════════════════════════
    # 3. ANTIBIOTICS — CEPHALOSPORINS
    # ═══════════════════════════════════════════════════════════
    "cefalexin":         _m("Antibiotic (1st gen Cephalosporin)",["Skin infections","UTI","Respiratory","Dental prophylaxis"],"500mg QID for 7 days",["amoxicillin","cloxacillin"],["Penicillin cross-reactivity (~1%)","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cefuroxime":        _m("Antibiotic (2nd gen Cephalosporin)",["Community pneumonia","UTI","Sinusitis","Otitis media"],"250–500mg BD (oral); 750mg–1.5g TDS (IV)",["amoxicillin_clavulanate","cefalexin"],["Penicillin cross-reactivity","GI upset","C. diff"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cefixime":          _m("Antibiotic (3rd gen Cephalosporin, oral)",["Typhoid","Gonorrhoea","UTI","Respiratory infections"],"200–400mg OD or BD",["cefpodoxime","amoxicillin"],["GI upset","Penicillin cross-reactivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cefpodoxime":       _m("Antibiotic (3rd gen Cephalosporin, oral)",["CAP","UTI","Sinusitis","Skin infections"],"100–200mg BD",["cefixime","amoxicillin_clavulanate"],["GI upset","Penicillin cross-reactivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ceftriaxone":       _m("Antibiotic (3rd gen Cephalosporin)",["Severe infections","Meningitis","Sepsis","Gonorrhoea","Typhoid"],"1–2g IV/IM OD",["cefotaxime","meropenem"],["Hypersensitivity","Biliary sludge","Penicillin cross-reactivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cefotaxime":        _m("Antibiotic (3rd gen Cephalosporin)",["Meningitis","Sepsis","Severe hospital infections","Neonatal sepsis"],"1–2g IV BD–QID",["ceftriaxone","meropenem"],["Penicillin cross-reactivity","C. diff","Seizures"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ceftazidime":       _m("Antibiotic (3rd gen Cephalosporin, anti-Pseudomonal)",["Pseudomonas infections","VAP","Febrile neutropenia","Melioidosis"],"1–2g IV TDS",["piperacillin_tazobactam","meropenem"],["Penicillin cross-reactivity","Seizures"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cefepime":          _m("Antibiotic (4th gen Cephalosporin)",["Febrile neutropenia","VAP","Sepsis","Pseudomonas"],"1–2g IV BD–TDS",["piperacillin_tazobactam","meropenem"],["Neurotoxicity (high dose/renal failure)","Penicillin cross-reactivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ceftaroline":       _m("Antibiotic (5th gen Cephalosporin, anti-MRSA)",["MRSA pneumonia","Complicated skin infections","Bacteraemia"],"600mg IV BD",["vancomycin","linezolid"],["Penicillin cross-reactivity","Haematological toxicity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),

    # ═══════════════════════════════════════════════════════════
    # 4. ANTIBIOTICS — MACROLIDES / LINCOSAMIDES
    # ═══════════════════════════════════════════════════════════
    "azithromycin":      _m("Antibiotic (Macrolide)",["Respiratory infections","Chlamydia","Skin infections","CAP"],"500mg OD for 3 days or Z-Pak",["clarithromycin","doxycycline"],["QT prolongation","GI upset","Liver caution"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "clarithromycin":    _m("Antibiotic (Macrolide)",["H. pylori","Respiratory","Skin infections","MAC prophylaxis"],"500mg BD for 7 days",["azithromycin","amoxicillin"],["QT prolongation","CYP3A4 interactions","Taste disturbance"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "erythromycin":      _m("Antibiotic (Macrolide)",["Penicillin allergy alternative","Respiratory","Skin","Chlamydia","Gastroparesis (off-label)"],"250–500mg QID",["azithromycin","clarithromycin"],["QT prolongation","GI upset","Drug interactions"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "clindamycin":       _m("Antibiotic (Lincosamide)",["Anaerobic infections","MRSA soft tissue","Dental infections","Bone infections","Toxoplasmosis (with pyrimethamine)"],"300–450mg QID",["metronidazole","amoxicillin_clavulanate"],["C. diff (high risk)","GI upset","Avoid if C. diff history"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "roxithromycin":     _m("Antibiotic (Macrolide)",["Respiratory tract infections","Sinusitis","Skin infections"],"150mg BD or 300mg OD",["azithromycin","clarithromycin"],["QT prolongation","GI upset","Fewer drug interactions than erythromycin"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "spiramycin":        _m("Antibiotic (Macrolide)",["Toxoplasmosis in pregnancy","Dental infections","Respiratory"],"3MU TDS",["clindamycin","azithromycin"],["GI upset","QT prolongation","Drug interactions"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),

    # ═══════════════════════════════════════════════════════════
    # 5. ANTIBIOTICS — FLUOROQUINOLONES
    # ═══════════════════════════════════════════════════════════
    "ciprofloxacin":     _m("Antibiotic (Fluoroquinolone)",["UTI","Typhoid","GI infections","Anthrax","Bone infections"],"500mg BD for 5–7 days",["levofloxacin","norfloxacin"],["Tendon rupture","QT prolongation","Photosensitivity","Avoid in children"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "levofloxacin":      _m("Antibiotic (Fluoroquinolone)",["CAP","UTI","Sinusitis","TB (second-line)"],"500–750mg OD",["ciprofloxacin","moxifloxacin"],["QT prolongation","Tendinopathy","Photosensitivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "moxifloxacin":      _m("Antibiotic (Fluoroquinolone)",["CAP","Skin infections","Intra-abdominal (with metronidazole)","TB (second-line)"],"400mg OD",["levofloxacin","ciprofloxacin"],["QT prolongation — do not use in arrhythmia","Avoid in hepatic failure"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "norfloxacin":       _m("Antibiotic (Fluoroquinolone)",["UTI","Traveller's diarrhoea","GI infections"],"400mg BD",["ciprofloxacin","ofloxacin"],["QT prolongation","Tendinopathy","Avoid in children","Photosensitivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ofloxacin":         _m("Antibiotic (Fluoroquinolone)",["UTI","Respiratory infections","STI","Ophthalmology (drops)"],"200–400mg BD",["ciprofloxacin","levofloxacin"],["QT prolongation","Tendinopathy","Photosensitivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "delafloxacin":      _m("Antibiotic (Fluoroquinolone)",["Skin/soft tissue infections","CAP (including MRSA)"],"300mg IV or 450mg PO BD",["vancomycin","linezolid"],["Hepatotoxicity","QT prolongation","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),

    # ═══════════════════════════════════════════════════════════
    # 6. ANTIBIOTICS — TETRACYCLINES & OTHERS
    # ═══════════════════════════════════════════════════════════
    "doxycycline":       _m("Antibiotic (Tetracycline)",["Malaria prophylaxis","Chlamydia","Acne","Lyme disease","Rickettsial","Brucellosis"],"100mg BD",["azithromycin","minocycline"],["Photosensitivity","Avoid in pregnancy/children","Oesophageal ulcer"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "minocycline":       _m("Antibiotic (Tetracycline)",["Acne","Skin infections","Rheumatoid arthritis (adjunct)"],"100mg BD",["doxycycline","azithromycin"],["Vestibular disturbance","Photosensitivity","Lupus-like syndrome","Avoid in women/children"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "tetracycline":      _m("Antibiotic (Tetracycline)",["H. pylori (quadruple therapy)","Acne","Chlamydia"],"250–500mg QID 1h before food",["doxycycline","minocycline"],["Avoid in pregnancy/children","Photosensitivity","Dairy chelation"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "metronidazole":     _m("Antibiotic (Nitroimidazole)",["Anaerobic infections","H. pylori","Giardia","Amoebiasis","BV"],"400mg TDS for 5–7 days",["tinidazole","secnidazole"],["Avoid alcohol (disulfiram reaction)","Metallic taste","Neuropathy (prolonged)"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "tinidazole":        _m("Antibiotic (Nitroimidazole)",["Giardiasis","Amoebiasis","BV","H. pylori","Anaerobic infections"],"2g stat or 500mg BD x5 days",["metronidazole","secnidazole"],["Avoid alcohol","Metallic taste","GI upset"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "secnidazole":       _m("Antibiotic (Nitroimidazole)",["Amoebiasis","Giardiasis","BV"],"2g stat (single dose)",["tinidazole","metronidazole"],["Avoid alcohol","GI upset","Single dose improves adherence"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "nitrofurantoin":    _m("Antibiotic (Nitrofuran)",["Lower UTI","UTI prophylaxis in pregnancy"],"50–100mg QID (5 days)",["cotrimoxazole","cefalexin"],["Pulmonary toxicity (long-term)","GI upset","Avoid at term pregnancy","Avoid in renal failure"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "cotrimoxazole":     _m("Antibiotic (Sulfonamide+TMP)",["UTI","Typhoid (limited)","PCP prophylaxis","Nocardia"],"480–960mg BD for 5–7 days",["ciprofloxacin","amoxicillin"],["SJS/TEN","Folate deficiency","Avoid in G6PD deficiency","Hyperkalaemia"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "trimethoprim":      _m("Antibiotic (Diaminopyrimidine)",["Uncomplicated UTI","RTI prophylaxis"],"200mg BD for 7 days",["nitrofurantoin","cotrimoxazole"],["Folate antagonism","Hyperkalaemia","Avoid in pregnancy 1st trimester"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "chloramphenicol":   _m("Antibiotic (Broad-spectrum)",["Typhoid (limited)","Meningitis (penicillin-allergic)","Eye drops — conjunctivitis"],"500mg QID; Eye drops 0.5% every 2h",["ceftriaxone","azithromycin"],["Aplastic anaemia","Grey baby syndrome","Bone marrow suppression"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "linezolid":         _m("Antibiotic (Oxazolidinone)",["MRSA","VRE","Drug-resistant TB (adjunct)","Nocardia"],"600mg BD IV/PO",["vancomycin","tedizolid"],["Serotonin syndrome (with SSRIs)","Myelosuppression","Optic neuropathy (>4 weeks)","Lactic acidosis"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "rifaximin":         _m("Antibiotic (Rifamycin, non-absorbed)",["Traveller's diarrhoea","HE (hepatic encephalopathy)","IBS-D","SIBO"],"200mg TDS (3 days) or 550mg BD (HE)",["metronidazole","cotrimoxazole"],["GI upset","Peripheral oedema in cirrhosis","C. diff (low risk)"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "fosfomycin":        _m("Antibiotic (Phosphonic acid)",["Uncomplicated UTI (single dose)","ESBL UTI","MRSA (IV)"],"3g sachet stat (UTI) or IV 4–6g TDS",["nitrofurantoin","cotrimoxazole"],["GI upset","Electrolyte disturbance (IV)","Generally well tolerated"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "nitazoxanide":      _m("Antiprotozoal/Antiviral",["Giardia","Cryptosporidium","Rotavirus","C. diff (adjunct)","Viral diarrhoea"],"500mg BD x3 days",["metronidazole","cotrimoxazole"],["GI upset","Yellow discolouration of sclerae (harmless)","Generally well tolerated"], ['Nausea', 'Headache', 'Fatigue'], 3),

    # ═══════════════════════════════════════════════════════════
    # 7. ANTIBIOTICS — AMINOGLYCOSIDES / CARBAPENEMS / GLYCOPEPTIDES
    # ═══════════════════════════════════════════════════════════
    "gentamicin":        _m("Antibiotic (Aminoglycoside)",["Severe Gram-negative infections","Sepsis","Endocarditis (synergy)"],"3–5mg/kg OD IV (once-daily)",["amikacin","tobramycin"],["Nephrotoxicity","Ototoxicity","Monitor levels","Avoid in pregnancy"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "amikacin":          _m("Antibiotic (Aminoglycoside)",["Multi-resistant Gram-negative infections","MDR-TB","Sepsis","Osteomyelitis"],"15–20mg/kg OD IV",["gentamicin","tobramycin"],["Nephrotoxicity","Ototoxicity","Monitor levels","Avoid in pregnancy"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "tobramycin":        _m("Antibiotic (Aminoglycoside)",["Pseudomonas eye/ear infections","CF lung disease","Gram-negative sepsis"],"3–5mg/kg OD IV; inhaled 300mg BD in CF",["gentamicin","amikacin"],["Nephrotoxicity","Ototoxicity","Monitor levels"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "meropenem":         _m("Antibiotic (Carbapenem)",["Severe sepsis","Hospital infections","Pseudomonas","Meningitis"],"1g IV TDS",["imipenem","ertapenem"],["Reserve for resistant organisms","Seizures (high dose)","Penicillin cross-reactivity rare"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "imipenem_cilastatin": _m("Antibiotic (Carbapenem)",["Severe hospital infections","Polymicrobial infections","Febrile neutropenia"],"500mg IV QID",["meropenem","ertapenem"],["Seizures (more than meropenem)","Reserve for resistant organisms"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "ertapenem":         _m("Antibiotic (Carbapenem)",["Community-acquired intra-abdominal infections","Complicated UTI","Diabetic foot — once-daily dosing"],"1g IV/IM OD",["meropenem","piperacillin_tazobactam"],["Not active vs Pseudomonas","Seizures","Reserve carbapenem"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "vancomycin":        _m("Antibiotic (Glycopeptide)",["MRSA","C. diff (oral)","Severe Gram+ infections"],"15–20mg/kg IV BD; 125mg PO QID (C. diff)",["linezolid","daptomycin"],["Nephrotoxicity","Ototoxicity","Red man syndrome — infuse slowly"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "teicoplanin":       _m("Antibiotic (Glycopeptide)",["MRSA","Gram+ severe infections","Endocarditis"],"400mg IV OD after loading",["vancomycin","linezolid"],["Nephrotoxicity (less than vancomycin)","Ototoxicity","Rash"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "daptomycin":        _m("Antibiotic (Lipopeptide)",["MRSA bacteraemia","Endocarditis","Complicated skin infections"],"4–6mg/kg IV OD",["vancomycin","linezolid"],["CPK elevation/myopathy (monitor)","Pneumonia — do not use (inactivated by surfactant)","Eosinophilic pneumonitis"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "colistin":          _m("Antibiotic (Polymyxin)",["Carbapenem-resistant infections","MDR Pseudomonas/Acinetobacter — last resort"],"CBA-based dosing IV TDS — specialist only",["tigecycline","fosfomycin"],["Nephrotoxicity","Neurotoxicity — last resort antibiotic","Resistance emerging"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "tigecycline":       _m("Antibiotic (Glycylcycline)",["Complicated skin/abdominal infections","MDR organisms — last resort"],"100mg IV loading then 50mg BD",["meropenem","colistin"],["GI upset","Increased all-cause mortality (serious infections)","Black box — non-inferior to comparators only"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),

    # ═══════════════════════════════════════════════════════════
    # 8. ANTIBIOTICS — ANTI-TB / ANTI-LEPROSY
    # ═══════════════════════════════════════════════════════════
    "rifampicin":        _m("Anti-TB",["Tuberculosis","Leprosy","Meningococcal prophylaxis"],"10mg/kg OD (max 600mg)",["isoniazid","ethambutol"],["Red-orange urine/fluids","Hepatotoxicity","Multiple drug interactions","Enzyme inducer"], ['Common clinical side effects'], 3),
    "isoniazid":         _m("Anti-TB",["TB treatment and prophylaxis"],"5mg/kg OD (max 300mg)",["rifampicin","pyrazinamide"],["Peripheral neuropathy (give Pyridoxine B6)","Hepatotoxicity","Lupus-like reaction"], ['Common clinical side effects'], 3),
    "pyrazinamide":      _m("Anti-TB",["Tuberculosis (initial 2-month DOTS phase)"],"25mg/kg OD (max 2g)",["isoniazid","rifampicin"],["Hepatotoxicity","Hyperuricaemia/gout","Arthralgia","Rash"], ['Common clinical side effects'], 3),
    "ethambutol":        _m("Anti-TB",["Tuberculosis (initial DOTS phase)"],"15–20mg/kg OD",["isoniazid","rifampicin"],["Optic neuritis — test vision monthly","Colour vision loss","Renal dose adjustment"], ['Common clinical side effects'], 3),
    "streptomycin":      _m("Anti-TB (Aminoglycoside)",["Drug-resistant TB","Plague","Brucellosis"],"15mg/kg IM OD",["amikacin","kanamycin"],["Ototoxicity","Nephrotoxicity","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "bedaquiline":       _m("Anti-TB (Diarylquinoline)",["MDR-TB (with other agents)"],"400mg OD x2 weeks then 200mg TDS — DOTS supervised",["delamanid","linezolid"],["QT prolongation","Hepatotoxicity","Nausea"], ['Common clinical side effects'], 3),
    "delamanid":         _m("Anti-TB (Nitroimidazole)",["MDR-TB (with other agents)"],"100mg BD x24 weeks — specialist only",["bedaquiline","linezolid"],["QT prolongation","Nausea","Anxiety"], ['Common clinical side effects'], 3),
    "dapsone":           _m("Anti-Leprosy/Dermatology",["Leprosy","PCP prophylaxis","Dermatitis herpetiformis","Acne vulgaris (topical)"],"100mg OD (leprosy); 50–100mg OD (PCP)",["proguanil","cotrimoxazole"],["Haemolysis in G6PD deficiency","Methaemoglobinaemia","Agranulocytosis","Peripheral neuropathy"], ['Common clinical side effects'], 3),
    "clofazimine":       _m("Anti-Leprosy",["Leprosy (multibacillary)","MDR-TB (adjunct)"],"50–300mg OD",["dapsone","rifampicin"],["Skin discolouration (pink-brown)","GI upset","QT prolongation","GI deposits"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 9. ANTIFUNGALS
    # ═══════════════════════════════════════════════════════════
    "fluconazole":       _m("Azole Antifungal",["Vaginal candidiasis","Oral thrush","Tinea","Cryptococcal meningitis"],"150mg stat (vaginal); 50–400mg OD (systemic)",["itraconazole","clotrimazole"],["QT prolongation","Hepatotoxicity","Multiple drug interactions","Teratogenic"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "itraconazole":      _m("Azole Antifungal",["Tinea","Onychomycosis","Aspergillosis","Histoplasmosis"],"100–200mg OD–BD with food",["fluconazole","terbinafine"],["Hepatotoxicity","Heart failure (negative inotrope)","Drug interactions","QT prolongation"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "ketoconazole":      _m("Azole Antifungal (Topical preferred)",["Dandruff (shampoo)","Seborrhoeic dermatitis","Tinea versicolor"],"Shampoo 2% twice/week; Tablet 200mg OD (restricted)",["itraconazole","fluconazole"],["Hepatotoxicity (tablets)","Drug interactions","Adrenal suppression"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "voriconazole":      _m("Azole Antifungal",["Invasive aspergillosis","Candida (serious)","Rare mould infections"],"4mg/kg IV BD (loading 6mg/kg BD Day1); 200mg PO BD",["posaconazole","amphotericin_b"],["Visual disturbances/hallucinations","Hepatotoxicity","QT prolongation","Drug interactions","Photosensitivity"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "posaconazole":      _m("Azole Antifungal",["Prophylaxis in immunocompromised","Invasive aspergillosis","Mucormycosis"],"300mg OD (delayed release tabs)",["voriconazole","amphotericin_b"],["QT prolongation","Hepatotoxicity","Drug interactions"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "isavuconazole":     _m("Triazole Antifungal",["Invasive aspergillosis","Mucormycosis"],"200mg TDS x2 days then 200mg OD",["voriconazole","posaconazole"],["QT shortening","Hepatotoxicity","Generally better tolerated than voriconazole"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "amphotericin_b":    _m("Polyene Antifungal",["Severe invasive fungal infections","Cryptococcal meningitis","Visceral leishmaniasis"],"0.7–1mg/kg IV OD (conventional) or Liposomal 3–5mg/kg",["voriconazole","caspofungin"],["Nephrotoxicity","Infusion-related reactions","Hypokalaemia","Anaemia"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "caspofungin":       _m("Echinocandin Antifungal",["Invasive candidiasis","Aspergillosis (salvage)","Febrile neutropenia (empirical)"],"70mg IV loading then 50mg OD",["micafungin","anidulafungin"],["Hepatotoxicity (rare)","Infusion-related reactions","Generally well tolerated"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "micafungin":        _m("Echinocandin Antifungal",["Invasive candidiasis","Candida prophylaxis in HSCT"],"100–150mg IV OD",["caspofungin","anidulafungin"],["Hepatotoxicity","Phlebitis","Generally well tolerated"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "terbinafine":       _m("Allylamine Antifungal",["Tinea pedis/cruris/corporis","Onychomycosis","Tinea capitis"],"250mg OD for 2–6 weeks (skin); 6–12 weeks (nails)",["itraconazole","fluconazole"],["Hepatotoxicity","GI upset","Taste disturbance","SJS (rare)"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "clotrimazole":      _m("Azole Antifungal (Topical)",["Vaginal candidiasis","Oral thrush","Tinea","Athlete's foot"],"Topical 1% cream BD; Pessary 500mg stat",["miconazole","fluconazole (oral)"],["Local irritation","Resistance possible"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "miconazole":        _m("Azole Antifungal (Topical/Oral gel)",["Oral candidiasis","Skin fungal infections","Nappy rash"],"Oral gel 2.5ml QID; Cream 2% BD",["clotrimazole","nystatin"],["Oral: drug interactions (warfarin)","Local irritation"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "nystatin":          _m("Polyene Antifungal (Topical/Oral)",["Oral candidiasis","Intestinal candidiasis","Nappy rash"],"100,000 units QID (oral rinse and swallow)",["clotrimazole","miconazole"],["GI upset (oral high dose)","Not absorbed — safe topically"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "griseofulvin":      _m("Antifungal (Oral, Keratin-affinity)",["Tinea capitis","Dermatophyte nail/skin infections"],"500mg OD–BD with fatty food",["terbinafine","itraconazole"],["Teratogenic — avoid in pregnancy","Photosensitivity","Drug interactions (warfarin)","Hepatotoxicity"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),

    # ═══════════════════════════════════════════════════════════
    # 10. ANTIVIRALS
    # ═══════════════════════════════════════════════════════════
    "aciclovir":         _m("Antiviral (Herpes)",["Herpes simplex (cold sores/genital)","Herpes zoster (shingles)","Varicella","HSV encephalitis"],"200mg 5x/day (HSV); 800mg 5x/day (VZV); IV 5–10mg/kg TDS",["valaciclovir","famciclovir"],["Nephrotoxicity (IV — hydrate well)","Neurotoxicity (IV)","GI upset"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "valaciclovir":      _m("Antiviral (Herpes — prodrug)",["Herpes labialis","Genital herpes","Herpes zoster","CMV prophylaxis"],"500mg BD (suppression); 1g TDS (shingles)",["aciclovir","famciclovir"],["Better bioavailability than aciclovir","Nephrotoxicity (high dose)","Headache"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "famciclovir":       _m("Antiviral (Herpes — prodrug)",["Herpes zoster","Genital herpes","Herpes labialis"],"500mg TDS for 7 days (shingles)",["valaciclovir","aciclovir"],["Headache","GI upset","Nephrotoxicity (rare)"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "oseltamivir":       _m("Antiviral (Influenza)",["Influenza A and B (treatment and prophylaxis)"],"75mg BD for 5 days (treatment); 75mg OD (prophylaxis)",["zanamivir","baloxavir"],["GI upset","Neuropsychiatric effects (rare — monitor in children)","Resistance (H275Y)"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "zanamivir":         _m("Antiviral (Influenza)",["Influenza A and B (inhaled)"],"10mg (2 inhalations) BD for 5 days",["oseltamivir","baloxavir"],["Bronchospasm — avoid in asthma/COPD","GI upset"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "baloxavir":         _m("Antiviral (Influenza — Cap endonuclease inhibitor)",["Influenza A and B (single dose)"],"40mg or 80mg (weight-based) stat",["oseltamivir","zanamivir"],["GI upset","Resistance possible","Single dose only"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "remdesivir":        _m("Antiviral (Adenosine analogue)",["COVID-19 (early hospitalisation)","Ebola (adjunct)"],"200mg IV Day 1 then 100mg OD x4 days",["nirmatrelvir_ritonavir","molnupiravir"],["Hepatotoxicity","Bradycardia","Infusion-related reactions","Nausea"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "nirmatrelvir_ritonavir": _m("Antiviral (Protease Inhibitor — Paxlovid)",["COVID-19 (mild-moderate, high risk of progression)"],"300mg + 100mg ritonavir BD x5 days — within 5 days of symptom onset",["remdesivir","molnupiravir"],["Drug interactions (ritonavir — CYP3A4)","Dysgeusia","Nausea","Contraindicated with CYP3A-sensitive drugs"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "molnupiravir":      _m("Antiviral (Mutagenic — RNA polymerase)",["COVID-19 (mild-moderate, high risk)"],"800mg BD x5 days",["nirmatrelvir_ritonavir","remdesivir"],["Teratogenic — avoid in pregnancy","GI upset","Unknown long-term mutagenic risk"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "tenofovir_alafenamide": _m("Antiviral (NRTI — HIV/HBV)",["HIV-1 infection (in combination)","Chronic hepatitis B"],"25mg OD — HIV regimens",["tenofovir_disoproxil","emtricitabine"],["Less nephrotoxicity than TDF","Bone density loss (less than TDF)","Lipid increase"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "tenofovir_disoproxil": _m("Antiviral (NRTI)",["HIV-1 (in combination)","Hepatitis B","PrEP"],"300mg OD",["tenofovir_alafenamide","zidovudine"],["Nephrotoxicity","Bone density loss","Fanconi syndrome"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "emtricitabine":     _m("Antiviral (NRTI)",["HIV-1 (in combination — component of Truvada/Descovy)","HBV"],"200mg OD (capsule) or 240mg OD (solution)",["lamivudine","tenofovir_alafenamide"],["Hyperpigmentation (palms/soles — Black patients)","Hepatitis flare (HBV — if stopped)","Generally well tolerated"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "lamivudine":        _m("Antiviral (NRTI)",["HIV-1 (in combination)","Hepatitis B"],"300mg OD or 150mg BD (HIV); 100mg OD (HBV)",["emtricitabine","tenofovir_disoproxil"],["Hepatitis flare (HBV)","GI upset","Peripheral neuropathy"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "dolutegravir":      _m("Antiviral (INSTI — HIV)",["HIV-1 treatment and salvage","HIV-1 2nd regimen"],"50mg OD or BD (with resistance)",["raltegravir","bictegravir"],["Insomnia","Neural tube defects (periconception)","GI upset","Weight gain"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "bictegravir":       _m("Antiviral (INSTI — HIV, component of Biktarvy)",["HIV-1 (Biktarvy = bictegravir/TAF/FTC)"],"50mg OD (in Biktarvy only)",["dolutegravir","raltegravir"],["Weight gain","Nausea","Neural tube defects risk (periconception)"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "efavirenz":         _m("Antiviral (NNRTI — HIV)",["HIV-1 (1st-line in developing countries)"],"600mg nocte (empty stomach — reduces CNS effects)",["nevirapine","rilpivirine"],["CNS effects (vivid dreams/dizziness)","Teratogenic","Rash","Drug interactions"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "sofosbuvir":        _m("Antiviral (NS5B polymerase — HCV)",["Hepatitis C (all genotypes — in combination regimens)"],"400mg OD (with daclatasvir/velpatasvir/ledipasvir)",["daclatasvir","ledipasvir"],["Bradycardia (with amiodarone — avoid)","Fatigue","Headache"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "daclatasvir":       _m("Antiviral (NS5A inhibitor — HCV)",["Hepatitis C genotype 1/3 (with sofosbuvir)"],"60mg OD",["sofosbuvir","velpatasvir"],["Bradycardia (with amiodarone)","GI upset","Drug interactions"], ['Nausea', 'Headache', 'Fatigue'], 3),
    "entecavir":         _m("Antiviral (Nucleoside analogue — HBV)",["Chronic hepatitis B"],"0.5mg OD fasting (treatment-naïve); 1mg OD (lamivudine-resistant)",["tenofovir_disoproxil","tenofovir_alafenamide"],["Lactic acidosis (rare)","Exacerbation on stopping — monitor LFTs"], ['Nausea', 'Headache', 'Fatigue'], 3),

    # ═══════════════════════════════════════════════════════════
    # 11. ANTIMALARIALS / ANTIPARASITIC
    # ═══════════════════════════════════════════════════════════
    "chloroquine":       _m("Antimalarial",["Malaria treatment/prophylaxis","Amoebic liver abscess","Rheumatoid arthritis/Lupus (HCQ preferred)"],"600mg base then 300mg at 6/24/48h",["quinine","artemether"],["Retinopathy (long-term)","QT prolongation","Avoid in G6PD deficiency"], ['Common clinical side effects'], 3),
    "hydroxychloroquine":_m("DMARD/Antimalarial",["Rheumatoid arthritis","Lupus","Malaria","Sjögren's"],"200–400mg OD",["methotrexate","chloroquine"],["Retinopathy (screen annually)","QT prolongation","GI upset"], ['Common clinical side effects'], 3),
    "artemether_lumefantrine": _m("Antimalarial (ACT)",["Uncomplicated P. falciparum malaria"],"4 tabs at 0,8,24,36,48,60h (adult) — 6 doses total",["artesunate","quinine"],["QT prolongation","GI upset","Headache"], ['Common clinical side effects'], 3),
    "artesunate":        _m("Antimalarial",["Severe P. falciparum malaria (IV/IM)","Uncomplicated malaria (oral, in combination)"],"2.4mg/kg IV at 0,12,24h then OD",["quinine","artemether_lumefantrine"],["Post-treatment haemolysis","GI upset","Neurotoxicity (high dose animal data)"], ['Common clinical side effects'], 3),
    "quinine":           _m("Antimalarial",["Severe P. falciparum malaria","Nocturnal leg cramps"],"650mg TDS for 7 days + doxycycline; IV for severe",["artesunate","artemether_lumefantrine"],["Cinchonism","QT prolongation","Hypoglycaemia","Bitter taste"], ['Common clinical side effects'], 3),
    "primaquine":        _m("Antimalarial",["P. vivax & ovale radical cure","Gametocidal — P. falciparum"],"15mg OD x14 days",["chloroquine","doxycycline"],["G6PD deficiency — MUST test first","Haemolysis","Methaemoglobinaemia","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "proguanil":         _m("Antimalarial (Prophylaxis)",["Malaria prophylaxis (with atovaquone or chloroquine)"],"200mg OD (with chloroquine) — start 1 week before travel",["doxycycline","mefloquine"],["Mouth ulcers","GI upset","Hair loss (rare)"], ['Common clinical side effects'], 3),
    "atovaquone_proguanil": _m("Antimalarial (Prophylaxis/Treatment)",["Malaria prophylaxis and treatment","PCP prophylaxis"],"Prophylaxis: 1 tab OD; Treatment: 4 tabs OD x3 days",["doxycycline","mefloquine"],["GI upset","Headache","Start 1–2 days before travel"], ['Common clinical side effects'], 3),
    "mefloquine":        _m("Antimalarial",["Malaria chemoprophylaxis (weekly)","Malaria treatment"],"250mg weekly (prophylaxis); 15–25mg/kg (treatment)",["doxycycline","atovaquone_proguanil"],["Neuropsychiatric effects","QT prolongation","Avoid in psychiatric history"], ['Common clinical side effects'], 3),
    "albendazole":       _m("Anthelmintic",["Tapeworm","Roundworm","Hookworm","Giardia","Hydatid disease","Neurocysticercosis"],"400mg stat (intestinal); 400mg BD x28 days (tissue)",["mebendazole","praziquantel"],["Hepatotoxicity","Bone marrow suppression","Teratogenic"], ['Common clinical side effects'], 3),
    "mebendazole":       _m("Anthelmintic",["Roundworm","Threadworm","Hookworm","Whipworm"],"100mg BD x3 days or 500mg stat",["albendazole","piperazine"],["GI upset","Avoid in children <1yr and pregnancy"], ['Common clinical side effects'], 3),
    "praziquantel":      _m("Anthelmintic/Antifluke",["Schistosomiasis","Tapeworm","Clonorchiasis","Cysticercosis"],"Schistosomiasis: 20mg/kg TDS x1 day; varies by indication",["albendazole"],["Abdominal pain","Dizziness","Headache"], ['Common clinical side effects'], 3),
    "ivermectin":        _m("Antiparasitic",["Strongyloidiasis","Scabies","Filariasis","Onchocerciasis","Head lice"],"200mcg/kg stat fasting",["albendazole","mebendazole"],["Mazzotti reaction in onchocerciasis","Neurological effects with P-gp inhibitors"], ['Common clinical side effects'], 3),
    "diethylcarbamazine":_m("Antifilarial",["Lymphatic filariasis","Loiasis","Tropical eosinophilia"],"6mg/kg/day in 3 divided doses x12 days",["ivermectin","albendazole"],["Mazzotti-like reaction","Encephalopathy in loiasis (high microfilaraemia)"], ['Common clinical side effects'], 3),
    "miltefosine":       _m("Antiprotozoal (Oral)",["Visceral leishmaniasis","Cutaneous/mucocutaneous leishmaniasis"],"2.5mg/kg/day for 28 days",["amphotericin_b","pentamidine"],["GI upset","Teratogenic — MUST avoid pregnancy","Hepatotoxicity","Renal toxicity"], ['Common clinical side effects'], 3),
    "pyrimethamine":     _m("Antiparasitic (Folate antagonist)",["Toxoplasmosis (with sulfadiazine/clindamycin)","Malaria (with sulfadoxine — Fansidar)"],"25–75mg OD (toxoplasmosis) — with folinic acid",["sulfadiazine","cotrimoxazole"],["Bone marrow suppression — give folinic acid","Megaloblastic anaemia","Teratogenic"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 12. CARDIOVASCULAR — ANTIHYPERTENSIVES
    # ═══════════════════════════════════════════════════════════
    "amlodipine":        _m("Calcium Channel Blocker",["Hypertension","Angina","Raynaud's phenomenon"],"5–10mg OD",["nifedipine","felodipine"],["Peripheral oedema","Flushing","Headache","Gingival hyperplasia"], ['Common clinical side effects'], 3),
    "nifedipine":        _m("Calcium Channel Blocker (DHP)",["Hypertension","Angina","Raynaud's","Pre-eclampsia"],"30–90mg OD (extended release)",["amlodipine","felodipine"],["Reflex tachycardia","Oedema","Headache","Flushing"], ['Common clinical side effects'], 3),
    "felodipine":        _m("Calcium Channel Blocker (DHP)",["Hypertension","Stable angina"],"5–10mg OD",["amlodipine","nifedipine"],["Oedema","Flushing","Headache","Grapefruit interaction"], ['Common clinical side effects'], 3),
    "diltiazem":         _m("Calcium Channel Blocker (Non-DHP)",["Hypertension","Angina","Atrial fibrillation rate control"],"60–120mg TDS or 180–360mg OD (SR)",["verapamil","amlodipine"],["Bradycardia","Heart block","Constipation","CYP3A4 interactions"], ['Common clinical side effects'], 3),
    "verapamil":         _m("Calcium Channel Blocker (Non-DHP)",["Angina","Hypertension","SVT","Atrial flutter/fibrillation"],"80–120mg TDS or 240–480mg OD (SR)",["diltiazem","beta-blockers (not combined)"],["Bradycardia","Heart block","Constipation","CONTRAINDICATED with beta-blockers"], ['Common clinical side effects'], 3),
    "atenolol":          _m("Beta Blocker",["Hypertension","Angina","Arrhythmia","Post-MI"],"50–100mg OD",["metoprolol","bisoprolol"],["Bradycardia","Avoid in asthma","Cold extremities","Masking hypoglycaemia"], ['Common clinical side effects'], 3),
    "metoprolol":        _m("Beta Blocker (Cardioselective)",["Hypertension","Heart failure","Post-MI","Migraine prevention"],"25–100mg BD",["atenolol","bisoprolol"],["Bradycardia","Avoid abrupt withdrawal","Asthma caution"], ['Common clinical side effects'], 3),
    "bisoprolol":        _m("Beta Blocker (Cardioselective)",["Heart failure","Hypertension","Angina"],"2.5–10mg OD",["metoprolol","carvedilol"],["Bradycardia","Fatigue","Cold extremities","Avoid in asthma"], ['Common clinical side effects'], 3),
    "carvedilol":        _m("Alpha+Beta Blocker",["Heart failure","Hypertension","Post-MI LV dysfunction"],"3.125–25mg BD",["bisoprolol","metoprolol"],["Bradycardia","Hypotension","Dizziness","Avoid in asthma"], ['Common clinical side effects'], 3),
    "labetalol":         _m("Alpha+Beta Blocker",["Hypertensive emergency","Hypertension in pregnancy","Pheochromocytoma"],"100–400mg BD; IV 50mg boluses",["hydralazine","methyldopa"],["Hepatotoxicity (rare)","Bradycardia","Postural hypotension"], ['Common clinical side effects'], 3),
    "enalapril":         _m("ACE Inhibitor",["Hypertension","Heart failure","Diabetic nephropathy"],"5–20mg OD or BD",["lisinopril","ramipril"],["Dry cough","Hyperkalaemia","Angioedema","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "lisinopril":        _m("ACE Inhibitor",["Hypertension","Heart failure","Post-MI"],"10–40mg OD",["enalapril","ramipril"],["Dry cough","Angioedema","Hyperkalaemia","Bilateral RAS contraindication"], ['Common clinical side effects'], 3),
    "ramipril":          _m("ACE Inhibitor",["Hypertension","Heart failure","High CV risk prevention","Post-MI"],"2.5–10mg OD",["lisinopril","enalapril"],["Dry cough","Angioedema","Hyperkalaemia","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "perindopril":       _m("ACE Inhibitor",["Hypertension","Heart failure","CV risk reduction","Stable CAD"],"4–8mg OD",["ramipril","lisinopril"],["Dry cough","Angioedema","Hyperkalaemia"], ['Common clinical side effects'], 3),
    "losartan":          _m("ARB",["Hypertension","Heart failure","Diabetic nephropathy","Stroke prevention in hypertensive+LVH"],"50–100mg OD",["valsartan","telmisartan"],["Hyperkalaemia","Renal impairment","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "valsartan":         _m("ARB",["Hypertension","Heart failure post-MI","LV dysfunction after MI"],"80–320mg OD",["losartan","telmisartan"],["Hyperkalaemia","Dizziness","Renal impairment"], ['Common clinical side effects'], 3),
    "telmisartan":       _m("ARB",["Hypertension","CV risk reduction","Diabetic nephropathy"],"40–80mg OD",["losartan","valsartan"],["Hyperkalaemia","Dizziness","Hepatic impairment"], ['Common clinical side effects'], 3),
    "candesartan":       _m("ARB",["Hypertension","Heart failure","Migraine prevention"],"4–32mg OD",["losartan","valsartan"],["Hyperkalaemia","Dizziness","Renal impairment"], ['Common clinical side effects'], 3),
    "olmesartan":        _m("ARB",["Hypertension"],"20–40mg OD",["losartan","telmisartan"],["Hyperkalaemia","Sprue-like enteropathy (rare)","Renal impairment"], ['Common clinical side effects'], 3),
    "sacubitril_valsartan": _m("ARNi",["Heart failure with reduced EF (HFrEF)"],"24/26mg to 97/103mg BD (titrate)",["enalapril","bisoprolol"],["Hypotension","Angioedema (NEVER with ACEI)","Hyperkalaemia","Renal impairment"], ['Common clinical side effects'], 3),
    "furosemide":        _m("Loop Diuretic",["Oedema","Heart failure","Hypertension","Pulmonary oedema"],"20–80mg OD or BD",["bumetanide","torsemide"],["Hypokalaemia","Dehydration","Ototoxicity (high dose)","Hyperuricaemia"], ['Common clinical side effects'], 3),
    "bumetanide":        _m("Loop Diuretic",["Oedema","Heart failure"],"0.5–2mg OD",["furosemide","torsemide"],["Hypokalaemia","Dehydration","Ototoxicity"], ['Common clinical side effects'], 3),
    "torsemide":         _m("Loop Diuretic",["Oedema","Heart failure","Hypertension"],"5–20mg OD",["furosemide","bumetanide"],["Hypokalaemia","Dehydration","Ototoxicity"], ['Common clinical side effects'], 3),
    "hydrochlorothiazide":_m("Thiazide Diuretic",["Hypertension","Oedema","Nephrogenic diabetes insipidus"],"12.5–25mg OD",["indapamide","chlorthalidone"],["Hypokalaemia","Hyponatraemia","Hyperglycaemia","Hyperuricaemia","Hyperlipidaemia"], ['Common clinical side effects'], 3),
    "indapamide":        _m("Thiazide-like Diuretic",["Hypertension","Oedema"],"1.5–2.5mg OD",["hydrochlorothiazide","chlorthalidone"],["Hypokalaemia","Hyponatraemia","Less metabolic effects then thiazides"], ['Common clinical side effects'], 3),
    "chlorthalidone":    _m("Thiazide-like Diuretic",["Hypertension","Oedema","Heart failure"],"12.5–50mg OD",["hydrochlorothiazide","indapamide"],["Hypokalaemia","Hyponatraemia","Hyperglycaemia","Long half-life advantage"], ['Common clinical side effects'], 3),
    "spironolactone":    _m("Potassium-sparing Diuretic/Aldosterone Antagonist",["Heart failure","Hyperaldosteronism","Oedema","Resistant hypertension","Acne (off-label)"],"25–100mg OD–BD",["eplerenone","amiloride"],["Hyperkalaemia","Gynaecomastia","Menstrual irregularity","Avoid with high K+ diet"], ['Common clinical side effects'], 3),
    "eplerenone":        _m("Selective Aldosterone Antagonist",["Post-MI heart failure","Hypertension","Heart failure"],"25–50mg OD",["spironolactone","amiloride"],["Hyperkalaemia","Less gynaecomastia than spironolactone"], ['Common clinical side effects'], 3),
    "amiloride":         _m("Potassium-sparing Diuretic",["Hypertension (with thiazide)","Prevention of hypokalaemia","Lithium-induced nephrogenic DI"],"5–10mg OD",["spironolactone","triamterene"],["Hyperkalaemia","GI upset"], ['Common clinical side effects'], 3),
    "doxazosin":         _m("Alpha Blocker",["Hypertension","BPH"],"1–16mg OD",["tamsulosin","prazosin"],["Postural hypotension (first-dose)","Dizziness","Oedema"], ['Common clinical side effects'], 3),
    "prazosin":          _m("Alpha Blocker",["Hypertension","BPH","PTSD nightmares"],"0.5–5mg BD–TDS",["doxazosin","terazosin"],["Severe first-dose hypotension","Dizziness","Fluid retention"], ['Common clinical side effects'], 3),
    "hydralazine":       _m("Vasodilator",["Hypertensive emergency","Heart failure","Pre-eclampsia"],"25–50mg QID",["amlodipine","labetalol"],["Lupus-like syndrome","Reflex tachycardia","Sodium retention"], ['Common clinical side effects'], 3),
    "methyldopa":        _m("Central Alpha-2 Agonist",["Hypertension in pregnancy (safe — preferred)"],"250mg–1g BD–TDS",["labetalol","nifedipine"],["Sedation","Haemolytic anaemia","Hepatitis","Positive Coombs test"], ['Common clinical side effects'], 3),
    "clonidine":         _m("Central Alpha-2 Agonist",["Hypertension","ADHD (off-label)","Opioid withdrawal","Pain (intrathecal)"],"75–300mcg BD–TDS",["methyldopa","guanfacine"],["Rebound hypertension on sudden withdrawal","Sedation","Dry mouth","Bradycardia"], ['Common clinical side effects'], 3),
    "minoxidil":         _m("Vasodilator",["Resistant hypertension (oral)","Male pattern baldness (topical)"],"Oral: 2.5–80mg OD; Topical: 5% solution BD",["hydralazine","doxazosin"],["Hypertrichosis","Fluid retention","Reflex tachycardia","Pericardial effusion"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 13. CARDIOVASCULAR — CARDIAC / LIPIDS / ANTICOAGULANTS
    # ═══════════════════════════════════════════════════════════
    "nitroglycerin":     _m("Nitrate",["Angina (acute)","Heart failure","Hypertensive emergency"],"0.5mg SL PRN; IV infusion for emergency",["isosorbide_dinitrate","isosorbide_mononitrate"],["Hypotension","Headache","CONTRAINDICATED with sildenafil/tadalafil"], ['Common clinical side effects'], 3),
    "isosorbide_dinitrate": _m("Nitrate",["Angina (chronic)","Heart failure"],"10–40mg TDS–QID; allow 8h nitrate-free interval",["nitroglycerin","isosorbide_mononitrate"],["Headache","Tolerance (nitrate-free period essential)","Hypotension"], ['Common clinical side effects'], 3),
    "isosorbide_mononitrate": _m("Nitrate",["Angina prevention"],"60–120mg OD or 20mg BD asymmetric dosing",["isosorbide_dinitrate","nitroglycerin"],["Headache","Tolerance (eccentric dosing prevents)","Hypotension"], ['Common clinical side effects'], 3),
    "digoxin":           _m("Cardiac Glycoside",["Heart failure","Atrial fibrillation (rate control)"],"0.125–0.25mg OD",["amiodarone","bisoprolol"],["Narrow therapeutic index","Toxicity (nausea/vision changes)","Hypokalaemia increases toxicity","Monitor levels"], ['Common clinical side effects'], 3),
    "amiodarone":        _m("Antiarrhythmic (Class III)",["Ventricular arrhythmia","AF","VT","VF resuscitation"],"200mg TDS (loading) then 200mg OD",["sotalol","flecainide"],["Thyroid dysfunction","Pulmonary toxicity","Photosensitivity","Hepatotoxicity","Multiple drug interactions","Corneal microdeposits"], ['Common clinical side effects'], 3),
    "sotalol":           _m("Beta Blocker/Antiarrhythmic (Class III)",["Ventricular arrhythmia","Atrial fibrillation","AF maintenance"],"80–160mg BD",["amiodarone","flecainide"],["QT prolongation","Torsades de Pointes","Bradycardia","Proarrhythmia"], ['Common clinical side effects'], 3),
    "flecainide":        _m("Antiarrhythmic (Class IC)",["AF (paroxysmal)","SVT","Wolff-Parkinson-White"],"50–200mg BD",["propafenone","amiodarone"],["Proarrhythmia — avoid post-MI/structural heart disease","Dizziness","Visual disturbances"], ['Common clinical side effects'], 3),
    "propafenone":       _m("Antiarrhythmic (Class IC)",["AF","SVT","Wolff-Parkinson-White"],"150–300mg TDS",["flecainide","amiodarone"],["Proarrhythmia — avoid structural heart disease","Taste disturbance","Bronchospasm"], ['Common clinical side effects'], 3),
    "adenosine":         _m("Antiarrhythmic",["SVT (termination)"],"6mg rapid IV (can repeat with 12mg)",["verapamil","beta blockers"],["Transient heart block","Bronchospasm — avoid in asthma","Chest discomfort — brief"], ['Common clinical side effects'], 3),
    "warfarin":          _m("Anticoagulant (Vitamin K Antagonist)",["DVT/PE","AF","Mechanical heart valves"],"2–10mg OD (dose per INR target)",["rivaroxaban","apixaban"],["Bleeding risk","Multiple interactions","INR monitoring essential","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "rivaroxaban":       _m("Anticoagulant (DOAC — Factor Xa)",["DVT/PE treatment and prevention","AF stroke prevention","Post-ACS"],"15mg BD (with food) for 3 weeks, then 20mg OD",["apixaban","dabigatran"],["Bleeding","No routine monitoring","Renal dose adjustment","Avoid in GFR < 15"], ['Common clinical side effects'], 3),
    "apixaban":          _m("Anticoagulant (DOAC — Factor Xa)",["DVT/PE","AF stroke prevention","VTE prophylaxis"],"10mg BD x7 days then 5mg BD (DVT/PE)",["rivaroxaban","dabigatran"],["Bleeding","No routine monitoring","Renal dose adjustment required"], ['Common clinical side effects'], 3),
    "dabigatran":        _m("Anticoagulant (DOAC — Direct Thrombin Inhibitor)",["AF stroke prevention","DVT/PE"],"150mg BD (or 110mg BD for 75+/high bleed risk)",["rivaroxaban","apixaban"],["Bleeding","Dyspepsia","Renal clearance — avoid GFR<30"], ['Common clinical side effects'], 3),
    "edoxaban":          _m("Anticoagulant (DOAC — Factor Xa)",["DVT/PE","AF stroke prevention"],"60mg OD (30mg if CrCl 15–50 or low bodyweight)",["rivaroxaban","apixaban"],["Bleeding","GI upset","Renal dose adjustment"], ['Common clinical side effects'], 3),
    "heparin":           _m("Anticoagulant",["DVT","PE","ACS","Surgical prophylaxis"],"LMWH: weight-based SC; UFH: 5000U SC BD–TDS or IV infusion",["enoxaparin","fondaparinux"],["Bleeding","HIT (heparin-induced thrombocytopaenia)","Monitor APTT (UFH)"], ['Common clinical side effects'], 3),
    "enoxaparin":        _m("Low Molecular Weight Heparin",["DVT/PE treatment","ACS","Surgical VTE prophylaxis"],"1mg/kg SC BD (treatment); 40mg SC OD (prophylaxis)",["heparin","fondaparinux"],["Bleeding","HIT (less than UFH)","Renal adjustment","Avoid in severe renal failure"], ['Common clinical side effects'], 3),
    "clopidogrel":       _m("Antiplatelet (P2Y12 Inhibitor)",["ACS","Post-stent","Stroke/TIA prevention","PAD"],"75mg OD (loading 300–600mg)",["ticagrelor","prasugrel"],["Bleeding risk","Avoid PPIs (omeprazole)","TTP (rare)"], ['Common clinical side effects'], 3),
    "ticagrelor":        _m("Antiplatelet (P2Y12 Inhibitor)",["ACS","Post-MI","High-risk CAD"],"90mg BD (loading 180mg) for ACS",["clopidogrel","prasugrel"],["Dyspnoea (common)","Bleeding","Bradycardia","Avoid in stroke haemorrhagic history"], ['Common clinical side effects'], 3),
    "prasugrel":         _m("Antiplatelet (P2Y12 Inhibitor)",["ACS with PCI","Post-stent"],"10mg OD (loading 60mg); 5mg OD if <60kg or >75yr",["clopidogrel","ticagrelor"],["Bleeding (more than clopidogrel)","Avoid in stroke/TIA history"], ['Common clinical side effects'], 3),
    "atorvastatin":      _m("Statin",["Hypercholesterolaemia","CV prevention","Post-MI","Stroke prevention"],"10–80mg OD",["rosuvastatin","simvastatin"],["Myopathy","Rhabdomyolysis","Hepatotoxicity","Avoid in pregnancy","Grapefruit interaction"], ['Common clinical side effects'], 3),
    "rosuvastatin":      _m("Statin",["High cholesterol","CV prevention"],"5–40mg OD (evening/any time)",["atorvastatin","simvastatin"],["Myopathy","Rhabdomyolysis (high dose)","Avoid in pregnancy","LFT monitoring"], ['Common clinical side effects'], 3),
    "simvastatin":       _m("Statin",["Hypercholesterolaemia","CV prevention"],"10–40mg nocte",["atorvastatin","rosuvastatin"],["Myopathy","Rhabdomyolysis","Avoid in pregnancy"], ['Common clinical side effects'], 3),
    "ezetimibe":         _m("Cholesterol Absorption Inhibitor",["Hypercholesterolaemia (with statin or alone)"],"10mg OD",["atorvastatin","evolocumab"],["GI upset","Myopathy (with statin)","Hepatotoxicity"], ['Common clinical side effects'], 3),
    "evolocumab":        _m("PCSK9 Inhibitor",["Familial hypercholesterolaemia","High CV risk — statin intolerant"],"140mg SC every 2 weeks or 420mg monthly",["alirocumab","ezetimibe"],["Injection site reactions","Nasopharyngitis","Expensive"], ['Common clinical side effects'], 3),
    "trimetazidine":     _m("Anti-Anginal (Metabolic)",["Angina (adjunct)","Cardiac ischaemia"],"35mg MR BD",["nitroglycerin","amlodipine"],["Parkinsonism/movement disorders","WADA banned in athletes","GI upset"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 14. DIABETES MELLITUS
    # ═══════════════════════════════════════════════════════════
    "metformin":         _m("Biguanide",["Type 2 Diabetes","PCOS","Insulin resistance"],"500–1000mg BD–TDS with food",["sitagliptin","glipizide"],["GI upset","Lactic acidosis (rare)","Withhold before contrast/surgery","B12 deficiency"], ['Common clinical side effects'], 3),
    "glibenclamide":     _m("Sulphonylurea",["Type 2 Diabetes"],"2.5–10mg OD before breakfast",["gliclazide","glipizide"],["Hypoglycaemia","Weight gain","Avoid in renal failure"], ['Common clinical side effects'], 3),
    "gliclazide":        _m("Sulphonylurea",["Type 2 Diabetes"],"40–160mg OD (MR 30–120mg OD)",["glibenclamide","sitagliptin"],["Hypoglycaemia","Weight gain"], ['Common clinical side effects'], 3),
    "glimepiride":       _m("Sulphonylurea",["Type 2 Diabetes"],"1–4mg OD with breakfast",["gliclazide","glibenclamide"],["Hypoglycaemia","Weight gain","Avoid in renal failure"], ['Common clinical side effects'], 3),
    "sitagliptin":       _m("DPP-4 Inhibitor",["Type 2 Diabetes"],"100mg OD",["vildagliptin","saxagliptin"],["Pancreatitis (rare)","Nasopharyngitis","Renal dose adjustment"], ['Common clinical side effects'], 3),
    "vildagliptin":      _m("DPP-4 Inhibitor",["Type 2 Diabetes"],"50mg BD",["sitagliptin","saxagliptin"],["Hepatotoxicity (monitor LFTs)","Nasopharyngitis","Pancreatitis (rare)"], ['Common clinical side effects'], 3),
    "empagliflozin":     _m("SGLT-2 Inhibitor",["Type 2 Diabetes","HFrEF","DKD"],"10–25mg OD",["dapagliflozin","canagliflozin"],["DKA (rare)","UTI/genital infections","Dehydration","Euglycaemic DKA"], ['Common clinical side effects'], 3),
    "dapagliflozin":     _m("SGLT-2 Inhibitor",["Type 2 Diabetes","Heart failure","CKD"],"10mg OD",["empagliflozin","canagliflozin"],["DKA","UTI/genital mycotic infections","Dehydration"], ['Common clinical side effects'], 3),
    "voglibose":         _m("Alpha-Glucosidase Inhibitor",["Type 2 Diabetes (post-prandial)","IGT"],"0.2–0.3mg TDS with meals",["acarbose","metformin"],["Flatulence","Diarrhoea","Avoid in bowel disease"], ['Common clinical side effects'], 3),
    "insulin_glargine":  _m("Insulin (Long-acting)",["Type 1 Diabetes","Type 2 Diabetes (basal)"],"Once daily SC at same time",["insulin_detemir","insulin_degludec"],["Hypoglycaemia (low nocturnal risk)","Injection site reactions","Weight gain"], ['Common clinical side effects'], 3),
    "insulin_aspart":    _m("Insulin (Rapid-acting)",["Mealtime insulin in T1/T2DM","Insulin pumps"],"SC before meals",["insulin_lispro","insulin_glulisine"],["Hypoglycaemia","Injection site reactions","Weight gain"], ['Common clinical side effects'], 3),
    "semaglutide":       _m("GLP-1 Receptor Agonist",["Type 2 Diabetes","Obesity (higher dose)","CV risk reduction"],"0.5–1mg SC weekly (Ozempic); 7–14mg OD oral (Rybelsus)",["dulaglutide","liraglutide"],["GI upset","Pancreatitis","Thyroid C-cell tumour risk","Weight loss"], ['Common clinical side effects'], 3),
    "liraglutide":       _m("GLP-1 Receptor Agonist",["Type 2 Diabetes","Obesity (3mg/day)","CV risk reduction"],"0.6–1.8mg SC OD",["semaglutide","dulaglutide"],["GI upset","Pancreatitis","Thyroid C-cell tumour risk"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 15. RESPIRATORY
    # ═══════════════════════════════════════════════════════════
    "salbutamol":        _m("Beta-2 Agonist (SABA)",["Asthma (acute)","COPD","Bronchoconstriction"],"2–4 puffs (100mcg) PRN; Nebule 2.5mg",["terbutaline","formoterol"],["Tremor","Tachycardia","Hypokalaemia (high dose)"], ['Common clinical side effects'], 3),
    "salmeterol":        _m("Beta-2 Agonist (LABA)",["Asthma maintenance (with ICS)","COPD"],"50mcg BD inhaled (must be with ICS in asthma)",["formoterol","vilanterol"],["Tachycardia","Never use alone in asthma"], ['Common clinical side effects'], 3),
    "budesonide":        _m("Inhaled Corticosteroid",["Asthma prevention","COPD","Croup"],"200–800mcg BD inhaled",["beclomethasone","fluticasone"],["Oral candidiasis","Dysphonia","Rinse mouth after use"], ['Common clinical side effects'], 3),
    "fluticasone":       _m("Inhaled Corticosteroid",["Asthma prevention","Allergic rhinitis (nasal)"],"100–500mcg BD inhaled",["budesonide","beclomethasone"],["Oral candidiasis","Dysphonia","Systemic effects at high dose"], ['Common clinical side effects'], 3),
    "tiotropium":        _m("Anticholinergic (LAMA)",["COPD maintenance","Asthma (add-on)"],"18mcg OD (HandiHaler) or 5mcg OD (Respimat)",["glycopyrronium","umeclidinium"],["Dry mouth","Urinary retention","Constipation","Glaucoma"], ['Common clinical side effects'], 3),
    "montelukast":       _m("Leukotriene Receptor Antagonist",["Asthma (adjunct)","Allergic rhinitis","EIB"],"10mg OD (evening)",["zafirlukast"],["Neuropsychiatric effects (rare)","GI upset"], ['Common clinical side effects'], 3),
    "theophylline":      _m("Xanthine",["Asthma","COPD"],"100–300mg BD–TDS (monitor levels)",["salbutamol","aminophylline"],["Narrow therapeutic index","Arrhythmias","Seizures","Multiple interactions"], ['Common clinical side effects'], 3),
    "acetylcysteine":    _m("Mucolytic/Antidote",["Productive cough","Paracetamol overdose (IV)","Contrast prophylaxis"],"600mg OD–BD (oral); IV per protocol",["bromhexine","ambroxol"],["GI upset","Anaphylactoid reactions (IV)","Rash"], ['Common clinical side effects'], 3),
    "ambroxol":          _m("Mucolytic",["Productive cough","COPD","Mucus hypersecretion"],"30mg TDS (oral); 15mg TDS (paediatric)",["bromhexine","carbocisteine"],["GI upset","Hypersensitivity (rare)"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 16. GASTROINTESTINAL
    # ═══════════════════════════════════════════════════════════
    "omeprazole":        _m("PPI",["GORD","Peptic ulcer","H. pylori","NSAID protection"],"20–40mg OD before breakfast",["pantoprazole","esomeprazole"],["Hypomagnesaemia","C. diff risk","Reduces clopidogrel efficacy","B12 deficiency"], ['Common clinical side effects'], 3),
    "pantoprazole":      _m("PPI",["GORD","Peptic ulcer","ZE syndrome","H. pylori"],"40mg OD before breakfast",["omeprazole","rabeprazole"],["Hypomagnesaemia","C. diff risk","B12 deficiency","Osteoporosis (long-term)"], ['Common clinical side effects'], 3),
    "ranitidine":        _m("H2 Blocker",["GORD","Peptic ulcer","ZE syndrome"],"150mg BD or 300mg nocte",["famotidine","omeprazole"],["Headache","Confusion in elderly","Less effective than PPIs"], ['Common clinical side effects'], 3),
    "ondansetron":       _m("5-HT3 Antagonist",["Nausea/Vomiting","Chemotherapy-induced nausea","Post-op nausea"],"4–8mg TDS",["metoclopramide","domperidone"],["Constipation","QT prolongation","Headache","Serotonin syndrome risk"], ['Common clinical side effects'], 3),
    "metoclopramide":    _m("Prokinetic/Antiemetic",["Nausea/Vomiting","Gastroparesis","Migraine (IV)","GORD"],"10mg TDS",["domperidone","ondansetron"],["Extrapyramidal effects","Tardive dyskinesia (prolonged)","Drowsiness"], ['Common clinical side effects'], 3),
    "domperidone":       _m("Prokinetic",["Nausea/Vomiting","Gastroparesis","Lactation"],"10mg TDS before meals",["metoclopramide","ondansetron"],["QT prolongation","Cardiac risk in elderly","Avoid in cardiac disease"], ['Common clinical side effects'], 3),
    "loperamide":        _m("Antidiarrhoeal",["Acute diarrhoea","Traveller's diarrhoea","IBS-D"],"4mg initially then 2mg after each loose stool (max 16mg)",["codeine","ORS"],["Avoid in bloody diarrhoea","Toxic megacolon in IBD","Abdominal bloating"], ['Common clinical side effects'], 3),
    "isabgol":           _m("Bulk-Forming Laxative (Psyllium Husk)",["Constipation","IBS","High cholesterol","Diabetes"],"1–2 tsp in water BD",["lactulose","bisacodyl"],["Flatulence","Bloating","Must take with water to prevent obstruction"], ['Common clinical side effects'], 3),
    "lactulose":         _m("Osmotic Laxative",["Constipation","Hepatic encephalopathy"],"15–30ml OD–BD (constipation); 30–50ml TDS (HE)",["macrogol","isabgol"],["Flatulence","Bloating","Cramps","Electrolyte imbalance"], ['Common clinical side effects'], 3),
    "bisacodyl":         _m("Stimulant Laxative",["Constipation","Bowel prep"],"5–10mg PO nocte or 10mg suppository",["senna","lactulose"],["Cramps","Electrolyte disturbance (prolonged)","Avoid long-term"], ['Common clinical side effects'], 3),
    "mesalazine":        _m("Aminosalicylate",["Ulcerative colitis","Crohn's colitis"],"1.2–2.4g OD or divided",["sulfasalazine","balsalazide"],["GI upset","Nephrotoxicity (monitor renal)","Headache","Male infertility"], ['Common clinical side effects'], 3),
    "ursodeoxycholic_acid": _m("Bile Acid",["PBC","Gallstone dissolution","GORD","Obstetric cholestasis"],"10–15mg/kg OD nocte",["colestyramine"],["GI upset","Diarrhoea","Generally well tolerated"], ['Common clinical side effects'], 3),
    "pancreatin":        _m("Pancreatic Enzyme",["Exocrine pancreatic insufficiency","CF","Chronic pancreatitis"],"Dose per lipase units per meal",["acid suppression adjunct"],["GI upset","Fibrosing colonopathy (high dose)","Perioral irritation"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 17. NEUROLOGY / PSYCHIATRY
    # ═══════════════════════════════════════════════════════════
    "levodopa_carbidopa": _m("Dopaminergic Agent",["Parkinson's disease"],"100/25mg TDS (titrate)",["pramipexole","ropinirole"],["Dyskinesia","Hallucinations","Orthostatic hypotension","On-off phenomenon"], ['Common clinical side effects'], 3),
    "pramipexole":       _m("Dopamine Agonist",["Parkinson's disease","Restless legs syndrome"],"0.125–1.5mg TDS",["ropinirole","levodopa"],["Sleep attacks","Impulse control disorders","Nausea","Hallucinations"], ['Common clinical side effects'], 3),
    "ropinirole":        _m("Dopamine Agonist",["Parkinson's disease","RLS"],"0.25–8mg TDS",["pramipexole","levodopa"],["Sleep attacks","Impulse control disorders","Syncope"], ['Common clinical side effects'], 3),
    "donepezil":         _m("Cholinesterase Inhibitor",["Alzheimer's disease (mild-moderate)"],"5–10mg nocte",["rivastigmine","galantamine"],["Insomnia","Bradycardia","GI upset (diarrhoea)","Vivid dreams"], ['Common clinical side effects'], 3),
    "rivastigmine":      _m("Cholinesterase Inhibitor",["Alzheimer's","Parkinson's dementia"],"1.5–6mg BD or 4.6–13.3mg/24h patch",["donepezil","galantamine"],["Nausea/vomiting (common)","Anorexia","Bradycardia"], ['Common clinical side effects'], 3),
    "memantine":         _m("NMDA Receptor Antagonist",["Alzheimer's disease (moderate-severe)"],"5–20mg OD",["donepezil"],["Dizziness","Confusion","Headache","Hallucinations"], ['Common clinical side effects'], 3),
    "phenytoin":         _m("Anticonvulsant",["Epilepsy (Tonic-clonic/Focal)","Status epilepticus"],"100mg TDS (monitor levels)",["carbamazepine","valproate"],["Gum hyperplasia","Ataxia","Nystagmus","Hirsutism","Teratogenic","SJS/TEN"], ['Common clinical side effects'], 3),
    "carbamazepine":     _m("Anticonvulsant",["Epilepsy","Trigeminal neuralgia","Bipolar disorder"],"200–400mg BD",["oxcarbazepine","valproate"],["Hyponatraemia","Leukopenia","SJS (HLA-B*1502 risk)","Enzyme inducer"], ['Common clinical side effects'], 3),
    "oxcarbazepine":     _m("Anticonvulsant",["Focal seizures"],"300–600mg BD",["carbamazepine","levetiracetam"],["Hyponatraemia (more than carbamazepine)","Dizziness","Sedation"], ['Common clinical side effects'], 3),
    "sodium_valproate":  _m("Anticonvulsant/Mood Stabiliser",["Epilepsy","Bipolar mania","Migraine prophylaxis"],"200–500mg BD",["carbamazepine","lamotrigine"],["Teratogenic (CRITICAL)","Hepatotoxicity","Weight gain","PCOS risk","Alopecia"], ['Common clinical side effects'], 3),
    "levetiracetam":     _m("Anticonvulsant",["Epilepsy (Focal/Generalised)"],"500–1500mg BD",["lamotrigine","valproate"],["Irritability/Psychosis","Somnolence","Dizziness","Suicidal ideation"], ['Common clinical side effects'], 3),
    "lamotrigine":       _m("Anticonvulsant",["Epilepsy","Bipolar depression"],"25–200mg OD/BD (titrate slowly)",["valproate","carbamazepine"],["SJS/TEN (Serious rash risk) — escalate slowly","Dizziness","Diplopia"], ['Common clinical side effects'], 3),
    "topiramate":        _m("Anticonvulsant",["Epilepsy","Migraine prophylaxis"],"25–100mg BD",["valproate","amitriptyline"],["Paresthesia","Weight loss","Cognitive slowing","Kidney stones","Glaucoma"], ['Common clinical side effects'], 3),
    "amitriptyline":     _m("TCA",["Depression","Neuropathic pain","Migraine prophylaxis","Insomnia"],"10–75mg nocte (pain); 75–150mg (depression)",["nortriptyline","duloxetine"],["Anticholinergic effects","Sedation","Weight gain","QT prolongation"], ['Common clinical side effects'], 3),
    "nortriptyline":     _m("TCA",["Depression","Neuropathic pain"],"10–50mg nocte (pain)",["amitriptyline","duloxetine"],["Less sedation/hypotension than amitriptyline","Dry mouth"], ['Common clinical side effects'], 3),
    "sertraline":        _m("SSRI",["Depression","Panic disorder","PTSD","OCD","GAD"],"50–200mg OD",["escitalopram","fluoxetine"],["Sexual dysfunction","Insomnia","GI upset","Serotonin syndrome","Withdrawal syndrome"], ['Common clinical side effects'], 3),
    "escitalopram":      _m("SSRI",["Depression","GAD","Panic disorder"],"10–20mg OD",["sertraline","fluoxetine"],["QT prolongation (max 20mg)","Sexual dysfunction","Nausea"], ['Common clinical side effects'], 3),
    "fluoxetine":        _m("SSRI",["Depression","OCD","Bulimia","PMDD"],"20–60mg OD",["sertraline","paroxetine"],["Insomnia","Agitation","Long half-life","Weight loss (initial)"], ['Common clinical side effects'], 3),
    "paroxetine":        _m("SSRI",["Depression","GAD","Panic disorder","Social anxiety"],"20–50mg OD",["sertraline","escitalopram"],["Highest sedation among SSRIs","Weight gain","Sexual dysfunction","Severe withdrawal"], ['Common clinical side effects'], 3),
    "venlafaxine":       _m("SNRI",["Depression","GAD","Social anxiety","Panic disorder"],"75–225mg OD (XR)",["desvenlafaxine","duloxetine"],["Hypertension (dose-dependent)","Withdrawal symptoms","Nausea"], ['Common clinical side effects'], 3),
    "desvenlafaxine":    _m("SNRI",["Major depressive disorder"],"50–100mg OD",["venlafaxine","duloxetine"],["Nausea","Sweating","Withdrawal symptoms"], ['Common clinical side effects'], 3),
    "mirtazapine":       _m("NaSSA",["Depression (with insomnia/anorexia)"],"15–45mg nocte",["sertraline","trazodone"],["Weight gain","Sedation","Appetite increase","Dry mouth"], ['Common clinical side effects'], 3),
    "quetiapine":        _m("Atypical Antipsychotic",["Bipolar disorder","Schizophrenia","Depression (adjunct)"],"25–300mg (bipolar); up to 800mg (schizophrenia)",["olanzapine","risperidone"],["Weight gain","Sedation","Metabolic syndrome","QT prolongation"], ['Common clinical side effects'], 3),
    "olanzapine":        _m("Atypical Antipsychotic",["Schizophrenia","Bipolar mania"],"5–20mg OD or nocte",["quetiapine","risperidone"],["Significant weight gain","Diabetes risk","Hyperlipidaemia","Anticholinergic effects"], ['Common clinical side effects'], 3),
    "risperidone":       _m("Atypical Antipsychotic",["Schizophrenia","Bipolar mania","Autism irritability"],"1–6mg OD or divided",["olanzapine","quetiapine"],["Hyperprolactinaemia (gynecomastia)","EPS (at high doses)","Weight gain"], ['Common clinical side effects'], 3),
    "aripiprazole":      _m("Atypical Antipsychotic (D2 Partial Agonist)",["Schizophrenia","Bipolar disorder","Depression (adjunct)"],"5–30mg OD",["quetiapine","brexpiprazole"],["Akathisia","Insomnia","Lower metabolic risk than olanzapine"], ['Common clinical side effects'], 3),
    "haloperidol":       _m("Typical Antipsychotic",["Schizophrenia","Psychosis","Tourette's","Delirium"],"0.5–10mg OD–TDS",["risperidone","olanzapine"],["High EPS risk","Tardive dyskinesia","QT prolongation","Hyperprolactinaemia"], ['Common clinical side effects'], 3),
    "lithium_carbonate": _m("Mood Stabiliser",["Bipolar disorder prophylaxis","Mania"],"600–1200mg OD/divided (target 0.6–1.0 mmol/L)",["valproate","quetiapine"],["Narrow therapeutic index","Thyroid toxicity","Renal toxicity","Tremor","Diabetes insipidus"], ['Common clinical side effects'], 3),
    "clozapine":         _m("Atypical Antipsychotic (Refractory)",["Treatment-resistant schizophrenia"],"12.5mg initially to 300–600mg (titrate)",["olanzapine","quetiapine"],["Agranulocytosis (MUST monitor FBC)","Seizures","Myocarditis","Sialorrhoea","Weight gain"], ['Common clinical side effects'], 3),
    "buspirone":         _m("Anxiolytic (5-HT1A Agonist)",["GAD"],"5–15mg BD–TDS",["SSRIs","alprazolam"],["Dizziness","Nausea","Delayed onset (2–4 weeks)","Non-addictive"], ['Common clinical side effects'], 3),
    "alprazolam":        _m("Benzodiazepine",["Panic disorder","Anxiety (short-term)"],"0.25–1mg TDS",["diazepam","lorazepam"],["Dependence","Sedation","Respiratory depression","Withdrawal seizures"], ['Common clinical side effects'], 3),
    "diazepam":          _m("Benzodiazepine",["Anxiety","Muscle spasm","Seizures","Alcohol withdrawal"],"2–10mg BD–QID",["lorazepam","alprazolam"],["Long half-life","Drowsiness","Addiction","Respiratory depression"], ['Common clinical side effects'], 3),
    "lorazepam":         _m("Benzodiazepine",["Anxiety","Status epilepticus","Insomnia"],"1–2mg BD–TDS",["diazepam","alprazolam"],["Dependence","Sedation","Short-medium acting","Respiratory depression"], ['Common clinical side effects'], 3),
    "clonazepam":        _m("Benzodiazepine/Anticonvulsant",["Panic disorder","Epilepsy","Social phobia","RLS"],"0.5–2mg OD–BD",["alprazolam","diazepam"],["Sedation","Dependence","Dizziness"], ['Common clinical side effects'], 3),
    "midazolam":         _m("Benzodiazepine (Short-acting)",["Sedation (procedural)","Status epilepticus"],"IV/IM/Buccal 1–5mg",["diazepam","lorazepam"],["Brief duration","Profound respiratory depression","Anterograde amnesia"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 18. ENDOCRINOLOGY / HORMONES / UROLOGY
    # ═══════════════════════════════════════════════════════════
    "levothyroxine":     _m("Thyroid Hormone (T4)",["Hypothyroidism","TSH suppression"],"25–150mcg OD fasting",["liothyronine"],["Hyperthyroid symptoms if overdose","Decreased bone mineral density","Cardiac arrhythmia"], ['Common clinical side effects'], 3),
    "carbimazole":       _m("Antithyroid Agent",["Hyperthyroidism","Graves' disease"],"5–20mg TDS (titrate down)",["methimazole","propylthiouracil"],["Agranulocytosis (sore throat!)","Hepatotoxicity","Teratogenic (1st trimester)"], ['Common clinical side effects'], 3),
    "propylthiouracil":  _m("Antithyroid Agent",["Hyperthyroidism (1st trimester pregnancy)","Thyroid storm"],"50–150mg TDS",["carbimazole"],["Severe hepatotoxicity (black box)","Agranulocytosis"], ['Common clinical side effects'], 3),
    "prednisolone":      _m("Glucocorticoid",["Inflammation","Autoimmune","Asthma","Allergy"],"5–60mg OD (titrate)",["methylprednisolone","dexamethasone"],["Adrenal suppression","Osteoporosis","Hyperglycaemia","Peptic ulcer","Infection risk"], ['Common clinical side effects'], 3),
    "methylprednisolone": _m("Glucocorticoid",["Severe inflammation","SCID","Asthma exacerbation"],"4–48mg OD; Pulse: 500mg–1g IV",["prednisolone","dexamethasone"],["Weight gain","Cushingoid features","Mood changes"], ['Common clinical side effects'], 3),
    "dexamethasone":     _m("Glucocorticoid (Potent)",["Cerebral oedema","Croup","Severe COVID-19","Antiemetic adjunct"],"0.5–10mg OD–TDS",["prednisolone"],["Hyperglycaemia","Insomnia","Gastritis"], ['Common clinical side effects'], 3),
    "hydrocortisone":    _m("Glucocorticoid/Mineralocorticoid",["Adrenal insufficiency (Addison's)","Emergency anaphylaxis"],"20–30mg daily divided (2/3 AM, 1/3 PM)",["prednisolone","fludrocortisone"],["Sodium retention","Oedema","Hypertension"], ['Common clinical side effects'], 3),
    "fludrocortisone":   _m("Mineralocorticoid",["Addison's disease","Postural hypotension"],"0.1mg OD",["hydrocortisone"],["Fluid retention","Hypertension","Hypokalaemia"], ['Common clinical side effects'], 3),
    "testosterone":      _m("Androgen",["Male hypogonadism"],"Gel 1% or Injection (undecanoate/enanthate)","clomifene",["Erythrocytosis (monitor Hct)","Prostate enlargement","Liver toxicity (oral)","Hair loss"]),
    "estradiol":         _m("Oestrogen",["HRT in menopause","Hypo-oestrogenism"],"1–2mg OD (oral/patch/gel)",["ethinylestradiol"],["VTE risk","Breast cancer risk","Uterine cancer risk (if no progestogen)"], ['Common clinical side effects'], 3),
    "progesterone":      _m("Progestogen",["HRT (with oestrogen)","Luteal support","Secondary amenorrhoea"],"100–200mg nocte",["medroxyprogesterone"],["Somnolence","Bloating","Breast tenderness"], ['Common clinical side effects'], 3),
    "medroxyprogesterone": _m("Progestogen",["Contraceptive (Depo)","Endometriosis","HRT"],"Depo: 150mg IM every 12 weeks",["norethisterone"],["Bone density loss","Weight gain","Delayed fertility return"], ['Common clinical side effects'], 3),
    "norethisterone":    _m("Progestogen",["Delaying menses","Abnormal uterine bleeding","Endometriosis"],"5mg TDS for 3–5 days (delay)",["levonorgestrel"],["DVT risk","Headache","GI upset"], ['Common clinical side effects'], 3),
    "levonorgestrel":    _m("Progestogen",["Emergency contraception","IUD (Mirena)","Contraceptive implant"],"1.5mg stat (within 72h)",["ulipristal"],["Nausea","Menstrual irregularities","Ectopic pregnancy risk (IUD)"], ['Common clinical side effects'], 3),
    "ulipristal":        _m("SPRM",["Emergency contraception (up to 120h)","Uterine fibroids"],"30mg stat (emergency)",["levonorgestrel"],["Headache","Dizziness","Hepatotoxicity (fibroid dose)"], ['Common clinical side effects'], 3),
    "clomifene":         _m("SERM",["Infertility (PCOS — ovulation induction)"],"50mg OD for 5 days (Day 2–6 of cycle)",["letrozole"],["Multiple pregnancy","Hot flushes","OHSS risk"], ['Common clinical side effects'], 3),
    "letrozole":         _m("Aromatase Inhibitor",["Breast cancer (hormone+)","Infertility (ovulation induction)"],"2.5mg OD",["anastrozole","clomifene"],["Joint pain","Osteoporosis","Hot flushes"], ['Common clinical side effects'], 3),
    "tamsulosin":        _m("Alpha-1A Blocker",["BPH (urinary symptoms)","Ureteric stone passage"],"0.4mg OD nocte",["silodosin","finasteride"],["Orthostatic hypotension","Retrograde ejaculation","Intraoperative floppy iris syndrome"], ['Common clinical side effects'], 3),
    "silodosin":         _m("Alpha-1A Blocker (Selective)",["BPH"],"4–8mg OD",["tamsulosin","finasteride"],["High rate of retrograde ejaculation","Dizziness","Orthostatic hypotension"], ['Common clinical side effects'], 3),
    "finasteride":       _m("5-Alpha Reductase Inhibitor",["BPH","Male pattern baldness"],"5mg OD (BPH); 1mg OD (hair)",["dutasteride","tamsulosin"],["Sexual dysfunction","Lower PSA","Gynaecomastia"], ['Common clinical side effects'], 3),
    "dutasteride":       _m("5-Alpha Reductase Inhibitor (Dual)",["BPH"],"0.5mg OD",["finasteride","tamsulosin"],["Sexual dysfunction","Lower PSA","Long half-life"], ['Common clinical side effects'], 3),
    "sildenafil":        _m("PDE-5 Inhibitor",["Erectile dysfunction","Pulmonary hypertension"],"50mg PRN (1h before); 20mg TDS (PAH)",["tadalafil","vardenafil"],["Headache","Blue-tinted vision","CONTRAINDICATED with nitrates"], ['Common clinical side effects'], 3),
    "tadalafil":         _m("PDE-5 Inhibitor (Long-acting)",["Erectile dysfunction","BPH","PAH"],"10–20mg PRN; 5mg OD (daily dose for BPH/ED)",["sildenafil","vardenafil"],["Headache","Back pain/myalgia","CONTRAINDICATED with nitrates"], ['Common clinical side effects'], 3),
    "desmopressin":      _m("ADH Analogue",["Cranial diabetes insipidus","Nocturnal enuresis","Von Willebrand disease"],"60–120mcg TDS oral; 10mcg nasal",["vasopressin"],["Hyponatraemia (water intoxication!)","Headache","GI upset"], ['Common clinical side effects'], 3),
    "tolvaptan":         _m("Vaptans (V2 Antagonist)",["SIADH","ADPKD (slow progression)"],"15mg OD (titrate up for ADPKD)",["furosemide"],["Thirst","Polyuria","Liver injury (black box)"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 19. DERMATOLOGY / TOPICAL / ALLERGY
    # ═══════════════════════════════════════════════════════════
    "cetirizine":        _m("Antihistamine (2nd gen)",["Allergic rhinitis","Urticaria","Allergy"],"10mg OD",["loratadine","fexofenadine"],["Mild sedation","Dry mouth","Dizziness"], ['Common clinical side effects'], 3),
    "levocetirizine":    _m("Antihistamine",["Allergic rhinitis","Chronic idiopathic urticaria"],"5mg OD",["cetirizine","fexofenadine"],["Somnolence","Fatigue","Dry mouth"], ['Common clinical side effects'], 3),
    "loratadine":        _m("Antihistamine",["Allergic rhinitis","Allergy"],"10mg OD",["desloratadine","fexofenadine"],["Non-sedating","Generally very well tolerated"], ['Common clinical side effects'], 3),
    "fexofenadine":      _m("Antihistamine",["Allergic rhinitis","Urticaria"],"120–180mg OD",["cetirizine","loratadine"],["Least sedating","Avoid with fruit juices"], ['Common clinical side effects'], 3),
    "chlorphenamine":    _m("Antihistamine (1st gen)",["Allergic reactions (acute)","Anaphylaxis adjunct"],"4mg every 4–6h; 10mg IV",["promethazine"],["Significant sedation","Anticholinergic effects"], ['Common clinical side effects'], 3),
    "isotretinoin":      _m("Retinoid",["Severe acne (nodulocystic)"],"0.5–1mg/kg OD x20 weeks (with lipids)",["tretinoin","benzoyl_peroxide"],["Teratogenic (CRITICAL)","Dry eyes/lips","Mood changes","Deranged LFTs/lipids"], ['Common clinical side effects'], 3),
    "tretinoin":         _m("Retinoid (Topical)",["Acne","Photoaging","Hyperpigmentation"],"Apply topically nocte",["isotretinoin","adapalene"],["Skin irritation/peeling","Photosensitivity"], ['Common clinical side effects'], 3),
    "adapalene":         _m("Retinoid (Topical 3rd gen)",["Acne"],"Apply topically nocte",["tretinoin","benzoyl_peroxide"],["Skin irritation (less than tretinoin)","Photosensitivity"], ['Common clinical side effects'], 3),
    "benzoyl_peroxide":  _m("Antiseptic (Topical)",["Acne vulgaris"],"2.5–10% gel OD–BD",["clindamycin","tretinoin"],["Skin dryness/irritation","Bleaches clothes/hair"], ['Common clinical side effects'], 3),
    "mupirocin":         _m("Topical Antibiotic",["Impetigo","MRSA decolonisation"],"2% cream/ointment TDS",["fusidic_acid"],["Local irritation","Resistance with long-term use"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "fusidic_acid":      _m("Topical Antibiotic",["Skin infections (Staphylococcal)"],"2% cream TDS",["mupirocin"],["Generally well tolerated","Local hypersensitivity"], ['Diarrhoea', 'Nausea', 'Rash', 'Stomach pain'], 4),
    "terbinafine_topical": _m("Antifungal",["Tinea","Athlete's foot","Pityriasis"],"1% cream/spray BD",["clotrimazole"],["Local irritation","Contact dermatitis"], ['Rash', 'Hepatotoxicity risks', 'GI upset'], 3),
    "hydrocortisone_topical": _m("Mild Corticosteroid",["Eczema","Dermatitis"],"0.5–2.5% cream BD",["betamethasone"],["Skin thinning (prolonged use)","Avoid on face if possible"], ['Common clinical side effects'], 3),
    "betamethasone_topical": _m("Potent Corticosteroid",["Severe eczema","Psoriasis"],"0.1% cream OD–BD",["hydrocortisone"],["Skin atrophy","Telangiectasia","HPA suppression"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 20. INDIAN SPECIFIC / AYURVEDIC
    # ═══════════════════════════════════════════════════════════
    "ashwagandha":        _m("Ayurvedic Adaptogen",["Stress","Anxiety","Fatigue","low testosterone"],"300–600mg extract OD",["brahmi"],["Thyroid stimulation","Avoid in pregnancy"], ['Generally safe, possible GI upset'], 1),
    "triphala":           _m("Ayurvedic Laxative/Detox",["Constipation","Digestive health"],"500mg–1g at bedtime",["isabgol"],["Diarrhoea in high dose","Avoid in pregnancy"], ['Generally safe, possible GI upset'], 1),
    "brahmi":             _m("Ayurvedic Nootropic",["Memory","Anxiety","Cognition"],"300–450mg OD",["ashwagandha"],["GI upset","Bradycardia (rare)"], ['Generally safe, possible GI upset'], 1),
    "guduchi":            _m("Ayurvedic Immunomodulator",["Immunity","Fever","Diabetes adjunct"],"500mg extract BD",["ashwagandha"],["Autoimmune flare risk","GI upset"], ['Generally safe, possible GI upset'], 1),
    "shatavari":          _m("Ayurvedic Female Tonic",["Hormone balance","Lactation"],"500mg OD–BD",["ashwagandha"],["GI bloating","Oestrogen-sensitive caution"], ['Generally safe, possible GI upset'], 1),
    "curcumin":           _m("Anti-inflammatory",["Arthritis","Inflammation"],"500–1000mg BD with piperine",["boswellia"],["GI upset","Anticoagulant interaction"], ['Common clinical side effects'], 3),
    "boswellia_serrata": _m("Herbal Anti-inflammatory",["Osteoarthritis","IBD"],"300–400mg TDS",["curcumin"],["GI upset","Rarely nausea"], ['Common clinical side effects'], 3),
    "amla":               _m("Vitamin C Source",["Immunity","Antioxidant","Hair"],"500mg OD",["triphala"],["GI upset in high dose"], ['Common clinical side effects'], 3),
    "tulsi":              _m("Ayurvedic Adaptogen",["Respiratory","Immunity","Stress"],"300mg extract OD",["ashwagandha"],["Anticoagulant interaction","Hypoglycaemia"], ['Generally safe, possible GI upset'], 1),
    "neem":               _m("Herbal Antiseptic",["Skin","Diabetes (adjunct)"],"500mg OD",["curcumin"],["Avoid in pregnancy","Toxic in infants"], ['Common clinical side effects'], 3),
    "gelusil":            _m("Antacid",["Acidity","Heartburn"],"1–2 tabs after meals",["digene"],["Constipation","Binds other drugs"], ['Common clinical side effects'], 3),
    "digene":             _m("Antacid",["Acidity","Gas"],"10ml after meals",["gelusil"],["Diarrhoea","Binds other drugs"], ['Common clinical side effects'], 3),
    "eno":                _m("Antacid (Efferent)",["Quick acidity relief"],"One sachet in water PRN",["gelusil"],["Sodium load","Alkalosis"], ['Common clinical side effects'], 3),
    "liv52":              _m("Hepatoprotective (Herbal)",["Liver dysfunction","Jaundice adjunct"],"2 tabs BD–TDS",["silymarin"],["Generally safe","Not a substitute for medical therapy"], ['Common clinical side effects'], 3),
    "cystone":            _m("Herbal Nephroprotective",["Kidney stones","UTI adjunct"],"2 tabs BD",["neeri"],["Adequate water intake essential"], ['Common clinical side effects'], 3),
    "septilin":           _m("Herbal Immunomodulator",["Recurrent infections","Immunity"],"2 tabs BD",["ashwagandha"],["Generally safe"], ['Common clinical side effects'], 3),

    # ═══════════════════════════════════════════════════════════
    # 21. MISCELLANEOUS / HAEMATOLOGY / VACCINES
    # ═══════════════════════════════════════════════════════════
    "ferrous_sulphate":   _m("Iron Supplement",["Iron deficiency anaemia"],"200mg TDS (65mg elemental iron x3)",["ferrous_fumarate","ferrous_gluconate"],["Constipation","Black stools","GI upset","Metallic taste"], ['Common clinical side effects'], 3),
    "folic_acid":         _m("Vitamin B9",["Folate deficiency anaemia","Neural tube defect prevention"],"5mg OD (deficiency); 400mcg OD (preconception)",["methylfolate"],["May mask B12 deficiency"], ['Common clinical side effects'], 3),
    "hydroxocobalamin":   _m("Vitamin B12",["B12 deficiency","Cyanide poisoning"],"1mg IM every 2 days x6 then every 3 months",["cyanocobalamin","methylcobalamin"],["Hypokalaemia","Arrhythmia"], ['Common clinical side effects'], 3),
    "methylcobalamin":    _m("Vitamin B12 (Active)",["Peripheral neuropathy","B12 deficiency"],"500–1500mcg OD",["cyanocobalamin"],["Generally well tolerated"], ['Common clinical side effects'], 3),
    "vitamin_d3":         _m("Vitamin (Cholecalciferol)",["D3 deficiency","Osteoporosis","Immunity"],"60,000 IU weekly x8 then monthly (deficiency)",["calcitriol"],["Hypercalcaemia (overdose)","Nausea"], ['Common clinical side effects'], 3),
    "calcitriol":         _m("Active Vitamin D",["Renal bone disease","Hypocalcaemia"],"0.25–0.5mcg OD",["vitamin_d3"],["High risk of hypercalcaemia","Monitor calcium levels"], ['Common clinical side effects'], 3),
    "calcium_carbonate":  _m("Mineral Supplement",["Calcium deficiency","Osteoporosis","Hyperphosphataemia"],"500mg BD–TDS with food",["calcium_citrate"],["Constipation","Bloating","Kidney stones"], ['Common clinical side effects'], 3),
    "epinephrine":        _m("Sympathomimetic",["Anaphylaxis (IM)","Cardiac arrest (IV)","Croup (Neb)"],"0.3–0.5mg IM (Anapen); 1mg IV (arrest)",["norepinephrine"],["Tachycardia","Arrhythmias","Cardiac ischaemia"], ['Common clinical side effects'], 3),
    "norepinephrine":     _m("Vasopressor",["Septic shock","Cardiogenic shock"],"IV infusion (titrate to MAP)",["epinephrine","dopamine"],["Tissue necrosis if extravasated","Cardiac workload increase"], ['Common clinical side effects'], 3),
    "dopamine":           _m("Vasopressor/Inotrope",["Shock","Bradycardia (refractory)"],"IV infusion (titrate)",["epinephrine","dobutamine"],["Tachyarrhythmias","Necrosis risk"], ['Common clinical side effects'], 3),
    "dobutamine":         _m("Inotrope (Beta-1 selective)",["Heart failure (acute)","Cardiogenic shock"],"IV infusion",["dopamine","milrinone"],["Tachycardia","PVCs","Hypokalaemia"], ['Common clinical side effects'], 3),
    "naloxone":           _m("Opioid Antagonist",["Opioid overdose reversal"],"0.4–2mg IV/IM; repeat every 2–3 min",["naltrexone"],["Acute opioid withdrawal","Short duration (repeat)"], ['Constipation', 'Sedation', 'Nausea', 'Dizziness'], 5),
    "activated_charcoal": _m("Adsorbent",["Acute poisoning"],"50g (adult) within 1–2h",["gastric_lavage"],["Aspiration risk","Constipation","Black stools"], ['Common clinical side effects'], 3),

}


